### ISSUE TITLE
Support v2 virtual table methods

### ISSUE THREAD

**Issue by rogerbinns** [rogerbinns/apsw#128]
_From [rogerbinns](https://code.google.com/u/rogerbinns/) on January 22, 2012 23:50:30_

Last 3 at http://www.sqlite.org/c3ref/module.html

_Original issue: http://code.google.com/p/apsw/issues/detail?id=128_

**Comment by cancan101** [comment]
Has this been completed? A quick check of the code base shows usage of the `_v2` variants. e.g
https://github.com/rogerbinns/apsw/blob/032cecf038c1700281746072dd8061bc4aab70dd/src/connection.c#L2968

**Comment by rogerbinns** [comment]
Nope.  This ticket is about the methods xSavepoint, xRelease etc.  There has been no demand for that hence no progress.

sqlite3_create_module_v2 differs from sqlite3_create_module (v1) in that a destructor callback is present, and has nothing to do with xSavepoint etc.  Back in those days SQLite C APIs were often added where the underlying expectation was items would live for the lifetime of the connection.  APSW had to keep track of the items and could only free them at connection close.  (This also happened with user defined functions and collation as examples.)   Having SQLite keep track of the item lifetimes and calling the APSW destructor let me delete that tracking code which was a pleasant improvement.
