### ISSUE TITLE
Improve pypy support

### ISSUE THREAD

**Issue by rogerbinns** [rogerbinns/apsw#129]
_From [Arfrever.FTA](https://code.google.com/u/103102260222931876118/) on February 04, 2012 12:38:32_

src/pypycompat.c is missing in apsw-3.7.10- r1 .zip. Please fix MANIFEST.in.

_Original issue: http://code.google.com/p/apsw/issues/detail?id=129_

**Comment by ldanielburr** [comment]
I know this issue is years old at this point, but there has been a great deal of progress with cpyext over the past 12 months, so I am wondering if apsw support for pypy is more readily achievable now.

**Comment by rogerbinns** [comment]
3.38.5-r1 has complete support for pypy, but pypy itself has some issues.  pypy works fine for most things now.
