### ISSUE TITLE
megatest failing with errors about "?ython"

### ISSUE THREAD

**Issue by msabramo** [rogerbinns/apsw#178]
```
$ python tools/megatest.py
Test starting
  ... removing old work directory
      done
...
sh: line 0: cd: ?ython-3.4.2: No such file or directory

FAILED {'pyver': '3.4.2', 'sqlitever': '3.8.8', 'workdir': '/Users/marca/dev/git-repos/apsw/work/py3.4.2-ucs0-sq3.8.8', 'ucs': 0, 'logdir': '/Users/marca/dev/git-repos/apsw/megatestresults/py3.4.2-ucs0-sq3.8.8'}
sh: line 0: cd: ?ython-3.4.2: No such file or directory

FAILED {'pyver': '3.4.2', 'sqlitever': '3.8.8.1', 'workdir': '/Users/marca/dev/git-repos/apsw/work/py3.4.2-ucs0-sq3.8.8.1', 'ucs': 0, 'logdir': '/Users/marca/dev/git-repos/apsw/megatestresults/py3.4.2-ucs0-sq3.8.8.1'}


sh: line 0: cd: ?ython-3.3.6: No such file or directory

FAILED {'pyver': '3.3.6', 'sqlitever': '3.8.8', 'workdir': '/Users/marca/dev/git-repos/apsw/work/py3.3.6-ucs0-sq3.8.8', 'ucs': 0, 'logdir': '/Users/marca/dev/git-repos/apsw/megatestresults/py3.3.6-ucs0-sq3.8.8'}
sh: line 0: cd: ?ython-3.3.6: No such file or directory

FAILED {'pyver': '3.3.6', 'sqlitever': '3.8.8.1', 'workdir': '/Users/marca/dev/git-repos/apsw/work/py3.3.6-ucs0-sq3.8.8.1', 'ucs': 0, 'logdir': '/Users/marca/dev/git-repos/apsw/megatestresults/py3.3.6-ucs0-sq3.8.8.1'}
```

Presumably it is coming from here:

```
$ ag '\?ython'
tools/megatest.py
169:    run("set -e ; LDFLAGS=\"-L/usr/lib/$(dpkg-architecture -qDEB_HOST_MULTIARCH)\"; export LDFLAGS ; cd %s ; cd ?ython-%s ; ./configure %s --disable-ipv6 --enable-unicode=ucs%d --prefix=%s/pyinst  >> %s 2>&1; make >>%s 2>&1; make  %sinstall >>%s 2>&1 ; make clean >/dev/null" % (workdir, pyver, opt, ucs, workdir, logfilename, logfilename, full, logfilename))
```

**Comment by rogerbinns** [comment]
I am not fixing this.  Use a shell that isn't broken.  What happened is that some Python releases extracted to a directory named Python-version and others to python-version, with this behaviour being almost random (eg between minor releases).  The question mark makes sure that whatever they did, it works.

os.system is invoking a shell on your system that isn't doing glob expansion.  Make it pick one that does.

**Comment by msabramo** [comment]
OK, well what shell would you recommend then?

- When I had `zsh` (5.0.7) as my shell originally it did not work.
- Switched it to `bash` (4.3.33) after your comment -- no dice:

```
marca@marca-mac2:~/dev/git-repos/apsw$ echo $SHELL
/usr/local/bin/bash
marca@marca-mac2:~/dev/git-repos/apsw$ /usr/local/bin/bash --version
GNU bash, version 4.3.33(1)-release (x86_64-apple-darwin13.4.0)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

Same problem.

Furthermore, I have doubts about your theory that the shell is the culprit.

```
marca@marca-mac2:~$ /bin/sh
sh-3.2$ mkdir /tmp/bourne_shell_wildcards
sh-3.2$ cd /tmp/bourne_shell_wildcards
sh-3.2$ touch Python-3.2
sh-3.2$ ls -l ?ython-3.2
-rw-r--r--  1 marca  wheel  0 Jan 30 17:34 Python-3.2
```

```
sh-3.2$ ls -l /bin/sh
-r-xr-xr-x  1 root  wheel  1228416 Nov 18 11:11 /bin/sh
sh-3.2$ /bin/sh --version
GNU bash, version 3.2.53(1)-release (x86_64-apple-darwin13)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**Comment by rogerbinns** [comment]
You can see in the megatest code that it calls os.system with the string.  Whatever is happening on your system is then causing the invoked shell to not do wildcard expansion.  You'll need to figure out why.  

This code has worked for over a decade for me.

**Comment by rogerbinns** [comment]
I just tried on Mac and other than not running some linux stuff (change just pushed) it runs just fine.  The machine was factory reset a few weeks ago and has no customisation like homebrew, .bashrc or anything else.  ie very vanilla.  This really is something on your system

**Comment by msabramo** [comment]
It works after adding `--no-proxy`. I hadn't noticed that it defaults to using a hard-coded proxy of http://192.168.1.25:8080 -- I'm not 100% sure but I think because of that it was failing to download the Python tarball. Maybe the proxy shouldn't be the default and it should instead get it from an environment variable?

I also had to add a missing checksum (see #179).

I still haven't gotten the tests to pass on my Mac, because it fails to compile zlib into the Pythons that it builds. Probably my system, since it works on your Mac.

But I did get it to work on an Ubuntu 14.04 VM. So that's cool.

**Comment by msabramo** [comment]
FYI: On OS X 10.9.5, one test fails for me:

```
======================================================================
ERROR: testICUExtension (tests.APSW)
Check ICU extension if present
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/marca/dev/git-repos/apsw/work/py2.7.9-ucs4-sq3.8.8/tests.py", line 1989, in testICUExtension
    if not self.checkOptionalExtension("icu", "select lower('I', 'tr_tr')"):
  File "/Users/marca/dev/git-repos/apsw/work/py2.7.9-ucs4-sq3.8.8/tests.py", line 1920, in checkOptionalExtension
    apsw.Connection(":memory:").cursor().execute(testquery)
  File "src/cursor.c", line 1016, in APSWCursor_execute.sqlite3_prepare
    AddTraceBackHere(__FILE__, __LINE__, "APSWCursor_execute.sqlite3_prepare", "{s: O, s: O}",
  File "src/statementcache.c", line 386, in sqlite3_prepare
    AddTraceBackHere(__FILE__, __LINE__, "sqlite3_prepare", "{s: N}", "sql", convertutf8stringsize(buffer, buflen));
SQLError: SQLError: wrong number of arguments to function lower()

----------------------------------------------------------------------
Ran 82 tests in 101.811s

FAILED (errors=1)
``` 

Any ideas?

**Comment by rogerbinns** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

On 01/31/2015 10:58 AM, Marc Abramowitz wrote:
> Maybe the proxy shouldn't be the default and it should instead get
> it from an environment variable?

I am the only one who ever runs that script - several times per
release, hence it defaults to being useful in my development environment.

> I also had to add a missing checksum (see #179 
> <https://github.com/rogerbinns/apsw/pull/179>).

That won't be accepted.

> I still haven't gotten the tests to pass on my Mac, because it
> fails to compile zlib into the Pythons that it builds. Probably my
> system, since it works on your Mac.

You need to install the xcode command line tools.  Something like
xcode-select --install should do the trick.

All tests pass fine, except one to do with ICU which I'll have to take
a closer look at.  (It looks like the build process thinks icu is
included in the extension when in fact it isn't.)

Roger

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iEYEARECAAYFAlTNXaoACgkQmOOfHg372QQBwgCgjtRkCjaM/LavNS7DMgOvGZtf
qhsAoN5ZB50nT2zRw79o9+LwEMVmbM9J
=H3WF
-----END PGP SIGNATURE-----
