### ISSUE TITLE
APSW does not support database encryption

### ISSUE THREAD

**Issue by desb42** [rogerbinns/apsw#183]
I have in other sqlite projects incorporated encryption using the SQLITE_HAS_CODEC flag 

Would there be any interest if I were to make a pull request to incorporate encryption

**Comment by rogerbinns** [comment]
I don't have the extension but was led to believe it is just appended to the amalgamation and works fine.  However on further reading it looks like -DSQLITE_HAS_CODEC is necessary too.  My preferred solution is to inspect the sqlite3.c file and then automatically add the flag.  Would this work for you?

If so, is there a known string I can scan the file for to know that SEE is present?

**Comment by rogerbinns** [comment]
Closing due to lack of response
