### ISSUE TITLE
setup.py build process has checksum errors (as of today)

### ISSUE THREAD

**Issue by tkhaew** [rogerbinns/apsw#185]
Here is output, just tried installing...  (on Ubuntu 12.04, after unzipping apsw-3.8.8.2-r1.zip)

python setup.py fetch --all build --enable-all-extensions install test
running fetch
  Getting download page to work out current SQLite version
    Fetching https://sqlite.org/download.html
    Version is 3.8.8.3
  Getting the SQLite amalgamation
    Fetching https://sqlite.org/2015/sqlite-autoconf-3080803.tar.gz
    Length: 2021112  SHA1: 2fe3f6226a2a08a2e814b97cd53e36bb3c597112  MD5: 51272e875879ee893e51070b07c33888
    (Not verified.  No match in checksums file)
Traceback (most recent call last):
  File "setup.py", line 868, in <module>
    'win64hackvars': win64hackvars}
  File "/usr/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 261, in run
    data=self.download(AURL, checksum=checksum)
  File "setup.py", line 452, in download
    self.verifyurl(url, page)
  File "setup.py", line 408, in verifyurl
    raise ValueError("No checksum available.  Use --missing-checksum-ok option to continue")
ValueError: No checksum available.  Use --missing-checksum-ok option to continue

**Comment by rogerbinns** [comment]
It is [working correctly](http://rogerbinns.github.io/apsw/build.html#fetch-checksums).  Your choices are:

* Run setup.py with --missing-checksum-ok flag
* Update the checksums
* Clone latest code which does have 3.8.8.3 checksums
* Use ```python setup.py fetch --version=3.8.8.2 --all build --enable-all-extensions install test``` (forcing version 3.8.8.2 which does have checksums)

SQLite 3.8.9 is coming out soon which is why I haven't done a version bump for 3.8.8.3
