### ISSUE TITLE
Add ASLR and DEP/NX compile flags to the default for windows

### ISSUE THREAD

**Issue by schlenk** [rogerbinns/apsw#192]
The ASLR and DEP/NX security features should be enabled by default on windows. Due to the outdated VS2008 compiler used by Python 2.7 this doesn't happen automatically.

Usually just adding /DYNAMICBASE and /NXCOMPAT to the linker flags are enough to enable it.

**Comment by rogerbinns** [comment]
Depending on the Python version, one of MinGW, VS2008 or VS2010 is used.  It is a horrendous pain getting it all working.  Also note that I am not actually using those VS versions, but rather a combination of the VS free version (limited in *many* ways) and the WIndows SDK which together allow 64 bit compilations to happen.

Anyway I will add those flags if you can figure out how to actually add them.  APSW just uses the standard distutils, so some voodoo with that would be needed, and also only for the appropriate compilers.

**Comment by schlenk** [comment]
Thanks. 

The linker flags should work out of the Box with VS2008 and VS2010, even in the crippled Express version. For mingw you might have luck with:

    LDFLAGS="-Wl,--nxcompat -Wl,--dynamicbase" 

There seem to be some issues for .exe files and mingw due to "--pie" but for .pyd and libraries it should just work.

**Comment by rogerbinns** [comment]
I can't figure out how to do this, or to test it in a reasonable way.
