### ISSUE TITLE
The BOM (byte order mark) is included in the first field name using the .autoimport command

### ISSUE THREAD

**Issue by cromoteca** [rogerbinns/apsw#194]
I imported a CSV file encoded as UTF-8 with [BOM](https://en.wikipedia.org/wiki/Byte_order_mark) and it has been added as an invisible character into the first field name. That makes it impossible to use that field by name in queries. I use Ubuntu 15.04 with default Python and SQLite packages.

**Comment by rogerbinns** [comment]
You need to use .encoding to set the encoding, not use a BOM.  If you set the encoding to utf8-sig then Python will strip the BOM which should fix your case.

**Comment by cromoteca** [comment]
Yes it fixed it even if only some of the files I need to process have the BOM, others not. Good to know. Thanks.
