### ISSUE TITLE
Best way to insert large volume of data with apsw?

### ISSUE THREAD

**Issue by Naatan** [rogerbinns/apsw#195]
I was using pysqlite before but it was too troublesome on windows. Apsw seems to work well but my existing code is insanely slow in comparison to pysqlite, I suspect because it's doing a large number of inserts. How would apsw have you handle this use case? 

I tried inserting multiple rows at once using the appropriate SQL syntax (VALUES (1), (2), (3), etc) but I ran into limits quickly.

**Comment by rogerbinns** [comment]
The most likely cause is that you aren't using transactions, hence each insert is its own transaction, which requires disk syncing etc.  Note that pysqlite parses your SQL and does all sorts of transaction stuff behind the scenes for you.

If you are creating a fresh database then I'd recommend turning off transactions completely (there is a pragma), insert all the data, then add indexes, constraints etc.  Finally turn transactions back on.

**Comment by Naatan** [comment]
That was indeed the issue, thank you for the swift response :)
