### ISSUE TITLE
Foreign key field

### ISSUE THREAD

**Issue by jodersus** [rogerbinns/apsw#200]
Hi,
How can I set a field to be a foreign key? I could not find it in the example or the rest of the documentation.

Thanks

**Comment by rogerbinns** [comment]
Foreign keys like virtually everything else are implemented in SQLite.  APSW just exposes what SQLite already has.  You can find the information by [searching for SQLite foreign keys](http://lmgtfy.com/?q=sqlite+foreign+keys)  which will lead you to the [SQLite documentation on foreign keys](https://www.sqlite.org/foreignkeys.html).

**Comment by jodersus** [comment]
Thanks for pointing to the docs, I had seen that just was not sure how to apply through apsw. I have ended up doing a few assumptions and trial and error got me there.

Sorry if I wasted your time.

**Comment by rogerbinns** [comment]
You didn't waste my time - no worries.  It does give me an opportunity to improve the documentation :-)
