### ISSUE TITLE
JSON1 and FTS5 support

### ISSUE THREAD

**Issue by lee-kagiso** [rogerbinns/apsw#201]
https://sqlite.org/amalgamation.html

If using the amalgamation will these newer extensions be automatically built?

Nothing is mentioned over here http://rogerbinns.github.io/apsw/build.html#build-build-ext when using the fetch flag?

**Comment by rogerbinns** [comment]
Those extensions will be added once they are  stable.  As of 3.9.2 FTS5 was not stable, and JSON1 just had serious bug fixes.

I think both are now stable for the 3.10.0 release, in which case they will be present in the corresponding APSW release.
