### ISSUE TITLE
Docs say not available on pypi, but I just pip installed?

### ISSUE THREAD

**Issue by lee-kagiso** [rogerbinns/apsw#202]
https://github.com/rogerbinns/apsw/blob/a422e522005a8a5f47b4862549e794b1437f9d09/doc/download.rst#easy_installpippypi

Is something amiss here? What gets installed now, latest sqlite with all extensions?

**Comment by rogerbinns** [comment]
Someone (rstuart85) else put up a version on pypi, briefly added text saying it wasn't official or by me (and wouldn't work for many users anyway), then removed that text so you can't tell, and left it languishing at some older version.

You forwarded an email from rstuart updating the version.  That however will again be out of date in a few days when 3.10.0 comes out.  Also what they did won't work well unless you are on exactly the same platform as them - fetching the amalgamation on non-Windows also runs configure, so the SQLite setup will be for whatever version of whatever OS they were using, likely some random version of MacOS,
