### ISSUE TITLE
Install doesn't find Python 3.5 on Windows 2012 Server

### ISSUE THREAD

**Issue by HarryPehkonen** [rogerbinns/apsw#203]
"Python version 3.5 required, which was not found in the registry."

I have it installed in C:\Program Files (x86)\Python35-32 (yes, seems to be the 32-bit version).  If I run either apsw-3.9.2-r1.win32-py3.5.exe or apsw-3.9.2-r1.win-amd64-py3.5.exe, I get the above error.

Fresh install of Python 3.5.1.

What can I do to troubleshoot?

Thanks!
Harry.

**Comment by rogerbinns** [comment]
It is a bug in Python 3.5.  http://bugs.python.org/issue25148
