### ISSUE TITLE
Building a redistributable wheel package

### ISSUE THREAD

**Issue by fillest** [rogerbinns/apsw#207]
Is there a way to do it? I've tried `python setup.py bdist` but the resulting tarball contains only .so and .egg-info.
The goal is to be able to build apsw (with the latest sqlite) on a target host once and then to be able to install it on the other hosts into a virtualenv during deploy without builing it on each host each time. Putting .so in the project directory can be inconvenient - for example we use a (legacy) `git pull` method to update the code and also clean all non-versioned files. I can exclude apsw files from cleaning but it feels hacky. It would be great to have a bit more convenient method.

**Comment by rogerbinns** [comment]
I'm confused as to what you are expecting.  The binary version of apsw is the .so and nothing else.  There are no accompanying .py files or similar.  The bdist output is correct.

**Comment by fillest** [comment]
How to install such bdist output except unpacking it into the working directory? How to conditionally update the package? I'm automating our deploy system, I need to update the package when the requirements change, do I have to manually track the version or to fetch and overwrite .so each time?
I've read the documentation section about easy_install/pip/pypi problems but e.g. `wheel` format is pretty standard now and I have full control over our internal PyPI server so I could use e.g. `python setup.py bdist_wheel` (which would produce a standardly installable distribution) if it would be supported by apsw..

**Comment by rogerbinns** [comment]
Ah, you confused me.  The bdist output really is correct, and pretty much identical to all the other bdist outputs (the .so and one or more metadata files).  But what you really want is supporting wheels.   For some reason they make you use setuptools instead of distutils.

**Comment by fillest** [comment]
Cool, thanks.

>Ah, you confused me
Sorry, I didn't know the exact solution at first and just tried to describe the goal.

**Comment by rogerbinns** [comment]
Do note that the bdist output really is correct.  What you do with it is no different than if you had a single .py file and made a bdist.  They aren't particularly convenient which is why there are other targets like bdist_rpm so you can turn it into a system package.

There will be an APSW 3.11.1 release soon (potentially within the next few hours).  You can either wait or apply the change from above to get the functionality.
