### ISSUE TITLE
Python 3 string problem in user defined functions

### ISSUE THREAD

**Issue by pdalloz** [rogerbinns/apsw#208]
The following code returns 0 for print(s.count(item)) until the print(s) statement is executed, and then it returns the correct value for print(s.count(item))

    import apsw

    connection=apsw.Connection("dbfile")
    cursor = connection.cursor()

    def TESTCOUNT(s, item):    
        print(s.count(item))
        print(s)
        print(s.count(item))
        return 'Done'
    
    connection.createscalarfunction("TESTCOUNT", TESTCOUNT)       

    for row in cursor.execute("select TESTCOUNT('abcdb','b')"):
        print(row)

OUTPUT:

    0
    abcdb
    2
    ('Done',)

This is windows 7, APSW 3.11.1-r1

**Comment by pdalloz** [comment]
Oops not 'virtual functions' .. should be 'user defined functions'

**Comment by rogerbinns** [comment]
I can repeat this on Linux too.  It doesn't happen with python 2.7 but does with 3.4.  Investigating.

**Comment by rogerbinns** [comment]
I have found the root cause, and it does fix this.  I need to do complete testing first to verify the completeness of the fix.  It is to do with PyUnicode_READY and you can read more in #132 and #168
