### ISSUE TITLE
apsw shell and .sqliterc

### ISSUE THREAD

**Issue by phdru** [rogerbinns/apsw#213]
1. Shouldn't apsw shell read .sqliterc automatically? Currently it doesn't.

2. I can do `apsw -init ~/.sqliterc` but I cannot do
```shell
$ apsw
SQLite version 3.8.7.1 (APSW 3.8.6-r1)
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> .read ~/.sqliterc
[Errno 2] No such file or directory: u'~/.sqliterc'
```
Shouldn't apsw shell expand tilde (and perhaps env vars) using os.path.expanduser and os.path.expandvars?

**Comment by rogerbinns** [comment]
> Shouldn't apsw shell expand tilde (and perhaps env vars) using os.path.expanduser and os.path.expandvars?

Nope.  The APSW shell follows the SQLite shell to the degree possible (which doesn't).  A script for one should work seamlessly for the other, unless you used a small number of the commands unique to each.

> Shouldn't apsw shell read .sqliterc automatically? Currently it doesn't.

Possibly although it should probably use a different filename

**Comment by phdru** [comment]
> > Shouldn't apsw shell expand tilde

> Nope. The APSW shell follows the SQLite shell to the degree possible (which doesn't). A script for one should work seamlessly for the other, unless you used a small number of the commands unique to each.

Ok. I see.
