### ISSUE TITLE
apsw shell unicode error during `.dump > file.sql`

### ISSUE THREAD

**Issue by WindfallLabs** [rogerbinns/apsw#219]
(This might likely be related to issue 108, but it was a few years old and closed.)  
The apsw shell.py fails with a UnicodeEncodeError (line 2426) when dumping to a file. Also, when colorama is installed, the last error points to File: ...\colorama\ansitowin32.py line 174.  
sqlite3.exe does not have these issues and I know you try to reproduce that experience as close as possible.  

Shell Code:  
`python shell.py test.sqlite .dump > shell_dump.sql` # this fails  
`sqlite3.exe test.sqlite .dump > sqlite_dump.sql` # this works  
Also, using `.output dump.sql` before `.dump` works just fine in apsw shell.py  

I'm attaching a small [Python script](https://gist.github.com/WindfallLabs/97b2fc24a8240344236d904f1a90b723) I used to test this via script, in case anyone finds it useful.  

(Edit: formatting)

**Comment by rogerbinns** [comment]
I tested this now and don't get an error, including when my encoding is set to ISO8859-1.  It probably helps that everything is Python 3
