### ISSUE TITLE
FAIL: testDBStatus (tests.APSW) Verify db status function Anaconda python 3.5.2

### ISSUE THREAD

**Issue by ebrown** [rogerbinns/apsw#221]
C:\Users\junk\git-repos\ext\apsw>git log -l 10
commit 09efaf5d25dbe431b50b838dcda34a0dfb16b34d
Author: Roger Binns <rogerb@rogerbinns.com>
Date:   Tue Aug 23 12:54:10 2016 -0700

    Version bump

=========================================================
                Python C:\Users\junk\AppData\Local\Continuum\Anaconda3\python.exe sys.version_info(major=3, minor=5, micro=2,
 releaselevel='final', serial=0)
Testing with APSW file C:\Users\junk\AppData\Local\Continuum\Anaconda3\lib\site-packages\apsw-3.14.1.post1-py3.5-win-amd64.eg
g\apsw.cp35-win_amd64.pyd
          APSW version 3.14.1-r1
    SQLite lib version 3.14.1
SQLite headers version 3014001
    Using amalgamation True
Not doing LoadExtension test.  You need to compile the extension first
  gcc -fPIC -shared -o testextension.sqlext -I. -Isqlite3 src/testextension.c
.....................F..............................................................
======================================================================
FAIL: testDBStatus (tests.APSW)
Verify db status function
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\junk\git-repos\ext\apsw\tests.py", line 3875, in testDBStatus
    self.assertTrue(res[0]<=res[1])
AssertionError: False is not true

----------------------------------------------------------------------
Ran 84 tests in 233.798s

**Comment by rogerbinns** [comment]
3.14 hasn't been released yet.  This is one of the issues already being worked on for the release.

The test that fails is due to changed behaviour in SQLite.  You can get various statistics from SQLite using that API.  It returns both the current value and the highwater mark.  The test double checks that the current value is less than or equal to the highwater mark.  As you see that is sometimes no longer the case.

**Comment by rogerbinns** [comment]
3.14.1-r1 has now been released, and includes an update to the tests so this no longer fails
