### ISSUE TITLE
Read only connection

### ISSUE THREAD

**Issue by dekhaus** [rogerbinns/apsw#222]
Hi

I need to open a connection to a SQLite db such that only read only queries can be performed using this connection (aka 'selects').  This stackoverflow question claims that apsw supports this capability ...

http://stackoverflow.com/questions/10205744/opening-sqlite3-database-from-python-in-read-only-mode

Is it possible to perform 'normal' selects in read-only mode using apsw ?

Thanks
Dave

**Comment by rogerbinns** [comment]
APSW doesn't change SQLite's behaviour, so whatever SQLite allows, apsw does too.

If you are asking how to open the database readonly,  see http://sqlite.org/c3ref/open.html

    db=apsw.Connection("database", flags=apsw.SQLITE_OPEN_READONLY)
