### ISSUE TITLE
APSW embedded into LibreOffice

### ISSUE THREAD

**Issue by mauriciobaeza** [rogerbinns/apsw#225]
I want to use apsw in LibreOffice 5.2

LibreOffice uses the core Py33

Download the same version of APSW from: https://github.com/rogerbinns/apsw/releases/download/3.15.2-r1/apsw-3.15.2-r1.win32-py3.3.exe

Added apsw.pyd in pythonpath in Macros into LibreOffice

When try import, I get next error:

Mensaje: <class 'ImportError'>: DLL load failed: No se puede encontrar el módulo especificado.

Which DLL need?

Thanks

**Comment by rogerbinns** [comment]
The APSW DLL from the site is self contained (ie includes SQLite as well).  It does not include the C runtime library as it links against the standard one used by the relevant Python version on Windows.  (You also cannot use different versions of the C runtime library in the same process - they must all be the same.)

There are two causes I can think of:

1. LibreOffice is changing where and how the .pyd file is found, so you'll need to figure that out.

2. (More likely) LibreOffice is using a different version of the C runtime library than the standard Python 3.3 distribution does.  (They compile up their own python and do not use the system one.)  In this case you have to recompile the library yourself using the LibreOffice python to ensure you end up with the same options and C runtime.

There is nothing I can do in APSW to address this.

**Comment by mauriciobaeza** [comment]
I think is option 2... thanks...
