### ISSUE TITLE
Segmentation fault on invalid path

### ISSUE THREAD

**Issue by esaulnier** [rogerbinns/apsw#227]
I ran into a seg fault using the code below when the apsw.Connection path is invalid. 

Using a valid path works without error.  I would like to be able to handle this exception gracefully without having to run that code in a separate process.

Here is the code:
```python
import sqlite3
import apsw
_connection = apsw.Connection(':memory:')
connection = sqlite3.connect(_connection)
destdb = apsw.Connection('some-file')  #Invalid path here causes a seg fault
with destdb.backup("main", _connection, "main") as backup:
    while not backup.done:
        backup.step(100)
```
From: 
https://lambdafu.net/2010/08/27/how-to-use-sqlites-backup-in-python/

**Comment by rogerbinns** [comment]
I only see the problem when mixing in pysqlite/sqlite3.  That module has removed support for passing an APSW connection instead of a string to connect, as it did some fairly hacky things behind the scenes.   Can you repeat this without pysqlite/sqlite3 involved?

**Comment by esaulnier** [comment]
Found this old thread that confirms that apsw/pysqlite connection sharing is experimental/not supported:
[https://groups.google.com/forum/#!topic/python-sqlite/LoCVHujopJ0](url)

Will refactor with APSW only and report back. 

On a side note: How do I make sure on Linux that both pysqlite and apsw share the same sqlite3 instance? 

It would be useful to expose the backup API to pysqlite but this is the wrong channel I guess.  

Thank you!

**Comment by rogerbinns** [comment]
Sharing sqlite3 is easiest done by building it as a shared library (default on Linux).  You can mix and match SQLite libraries (eg having one buried in APSW while also having a system one) although opening the same database from both in the same process may cause problems.

I think they did add backup to pysqlite at one point, although you'll then need to ensure you are using that version of it.

I'm closing this ticket.  Please re-open if you do find an APSW problem.  APSW includes tests like your code, so it will fundamentally work.
