### ISSUE TITLE
Cannot enable ICU support on macOS

### ISSUE THREAD

**Issue by poliquin** [rogerbinns/apsw#230]
EDIT: See comment below, which explains a solution to the issue, before studying this.

I am trying to build and install `apsw` with the ICU extension on macOS 10.12.3 (Sierra) using an Anaconda virtual environment and getting errors when trying to `import apsw` post-install:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/username/anaconda/lib/python3.5/site-packages/apsw-3.17.0.post1-py3.5-macosx-10.6-x86_64.egg/apsw.cpython-35m-darwin.so, 2): Library not loaded: libicui18n.54.dylib
  Referenced from: /Users/username/anaconda/lib/python3.5/site-packages/apsw-3.17.0.post1-py3.5-macosx-10.6-x86_64.egg/apsw.cpython-35m-darwin.so
  Reason: image not found
```

This is puzzling because I have the referenced library:

```
$ ls ~/anaconda/lib/libicui18n.54.dylib
/Users/username/anaconda/lib/libicui18n.54.dylib
```

And `icu-config` seems normal...

```
$ icu-config --cppflags
-I/Users/username/anaconda/include

$ icu-config --ldflags
 -L/Users/username/anaconda/lib -licui18n -licuuc -licudata
```

```
$ icuinfo
 <icuSystemParams type="icu4c">
    <param name="copyright"> Copyright (C) 2014, International Business Machines Corporation and others. All Rights Reserved. </param>
    <param name="product">icu4c</param>
    <param name="product.full">International Components for Unicode for C/C++</param>
    <param name="version">54.1</param>
    <param name="version.unicode">7.0</param>
    <param name="platform.number">3500</param>
    <param name="platform.type">Darwin</param>
    <param name="locale.default">en_US</param>
    <param name="locale.default.bcp47">en-US</param>
    <param name="converter.default">UTF-8</param>
    <param name="icudata.name">icudt54l</param>
    <param name="icudata.path"></param>
    <param name="cldr.version">26.0</param>
    <param name="tz.version">2014h</param>
    <param name="tz.default">America/New_York</param>
    <param name="cpu.bits">64</param>
    <param name="cpu.big_endian">0</param>
    <param name="os.wchar_width">4</param>
    <param name="os.charset_family">0</param>
    <param name="os.host">i386-apple-darwin9.8.0</param>
    <param name="build.build">i386-apple-darwin9.8.0</param>
    <param name="build.cc">gcc-4.2</param>
    <param name="build.cxx">g++-4.2</param>
    <param name="uconfig.internal_digitlist">1</param>
    <param name="uconfig.have_parseallinput">1</param>
    <param name="uconfig.format_fastpaths_49">1</param>
 </icuSystemParams>


ICU Initialization returned: U_ZERO_ERROR
```

I tried using ICU 58.2 from Homebrew by editing `setup.py` to call `/usr/local/Cellar/icu4c/58.2/bin/icu-config` instead of the Anaconda ICU, but the version of ICU referenced by the compiled library is still the Anaconda version and I end up with the same error.

I have tried tinkering with `$PATH`, but that hasn't worked either.

By the way, I can compile `apsw` and pass all tests without ICU support. Also, I can build `apsw` with ICU support if I use the macOS system Python (2.7.10) and it passes all tests (including the extension tests). In this case, it selects the Homebrew ICU.

Recap:
1. Any tips for getting the ICU extension working on macOS with Anaconda Python?
2. I think everything would work if I could somehow get `setup.py` to use my Homebrew ICU. But with the Anaconda virtual environment enabled, it always seems to use the Anaconda ICU library even if I give `setup.py` the full path to the Homebrew `icu-config`.

**Comment by poliquin** [comment]
Quick follow up...

I can get everything working if I build and install `apsw` in a non-root Anaconda virtual environment. So there is some issue with linking to the library when using the Anaconda root environment.

I guess this is not an `apsw` issue, but perhaps a note about this belongs in the documentation for people who want to use `apsw` with Anaconda python?

**Comment by rogerbinns** [comment]
The original issue is most likely not the ICU shared library but that it in turn links to something else and that isn't being found.  Linking on Mac also has many many weird quirks.  It isn't clear exactly what should be documented or how helpful it would be (eg which combinations of platforms, versions etc apply).  This report will serve as the documentation for the moment.

You also don't need to jump through quite as many hoops - once you have apsw.so (or whatever the extension) it can be copied and used easily without the compilation environment being present.
