### ISSUE TITLE
Cannot install APSW due to SSL verification error on sqlite.org

### ISSUE THREAD

**Issue by smspillaz** [rogerbinns/apsw#231]
```
pip install https://github.com/rogerbinns/apsw/releases/download/3.17.0-r1/apsw-3.17.0-r1.zip --global-option=fetch --global-option=--version --global-option=3.17.0 --global-option=--all --global-option=build --global-option=--enable-all-extensions
(redacted)virtualenv/lib/python3.5/site-packages/pip/commands/install.py:194: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Collecting https://github.com/rogerbinns/apsw/releases/download/3.17.0-r1/apsw-3.17.0-r1.zip
  Downloading https://github.com/rogerbinns/apsw/releases/download/3.17.0-r1/apsw-3.17.0-r1.zip (689kB)
    100% |████████████████████████████████| 696kB 2.0MB/s 
Installing collected packages: apsw
  Running setup.py install for apsw ... error
    Complete output from command (redacted)/virtualenv/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/var/folders/3x/5l69_w4s02g8gcbpj25yfvsh0000gn/T/pip-6i_betdq-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" fetch --version 3.17.0 --all build --enable-all-extensions install --record /var/folders/3x/5l69_w4s02g8gcbpj25yfvsh0000gn/T/pip-jf8pg4xf-record/install-record.txt --single-version-externally-managed --compile --install-headers (redacted)/virtualenv/bin/../include/site/python3.5/apsw:
    (redacted)/virtualenv/lib/python3.5/site-packages/setuptools/dist.py:333: UserWarning: Normalizing '3.17.0-r1' to '3.17.0.post1'
      normalized_version,
    running fetch
      Getting the SQLite amalgamation
        Fetching https://sqlite.org/2017/sqlite-autoconf-3170000.tar.gz
           Error  <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)>
            Try # 2
           Error  <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)>
            Try # 3
           Error  <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)>
            Try # 4
           Error  <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)>
            Try # 5
           Error  <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)>
    error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)>
```

**Comment by rogerbinns** [comment]
The SSL verification is being done by Python and openssl not APSW code.  You should not be getting certificate failures.  There are many possible reasons including your clock being off, and someone upstream of you modifying the traffic.  I strongly recommend that you figure out the cause.

If you just want to work around it, then you have the following options:

* Edit setup.py to change the https to http
* Download SQLite yourself and put it somewhere the build will find it:  https://rogerbinns.github.io/apsw/build.html#finding-sqlite-3

**Comment by smspillaz** [comment]
@rogerbinns Yeah, we're just working around it for now. Concerning though. Can you confirm that the certificate validation works for you? It's not working for my team in two different locations :/

**Comment by rogerbinns** [comment]
Certificate validation worked for me on Windows and Linux.  The build & test process for each release does so including across all the Python versions (2.3 - 3.6) although earlier 2.x releases don't validate.  I just did a retest on Linux and it is validating the certificate just fine.

It looks like SQLite switched to Lets Encrypt on March 13th so maybe you are experiencing issues with that?  The other possibility is your network infrastructure intercepts SSL connections and does things to them (various anti-virus, corporate compliance, intrusion detection etc products do this).

**Comment by pvilas** [comment]
The certificate doesn't work for me

`Fetching https://sqlite.org/2017/sqlite-autoconf-3210000.tar.gz
           Error  <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)>`

**Comment by rogerbinns** [comment]
The SQLite site hasn't changed.  It still uses letsencrypt.  The site does have SSL configured correctly:  https://www.ssllabs.com/ssltest/analyze.html?d=sqlite.org&s=45.33.6.223&latest

**Comment by pvilas** [comment]
Ok. It fails only when you try to install on a virtualenv (python 3.5). I have removed the --user of the pip.
`pip install https://github.com/rogerbinns/apsw/releases/download/3.21.0-r1/apsw-3.21.0-r1.zip \
--global-option=fetch --global-option=--version --global-option=3.21.0 --global-option=--all \
--global-option=build --global-option=--enable-all-extensions`
