### ISSUE TITLE
csv extension support

### ISSUE THREAD

**Issue by deecay** [rogerbinns/apsw#232]
Hi,

1. I would love to see csv extension included in `--enable-all-extensions`.
2. I have tried to put pre-compiled csv.so and tried to load it in Python by `c.execute("SELECT load_extension('csv')")` but got `SQLError: not authorized`. How can I enable pre-compiled csv from python?

**Comment by rogerbinns** [comment]
I'll examine the extension to see if the size and functionality is worth it (especially how mature and tested it is).

The answer to part 2 is https://rogerbinns.github.io/apsw/connection.html#apsw.Connection.enableloadextension

**Comment by deecay** [comment]
Thanks for the help on part 2!

**Comment by kmedcalf** [comment]
Be careful including extensions in APSW that are not part of the distribution.  I suspect that I am not the only one with a custom build procedure that includes a raft of extensions in the build and just like when Richard includes the same extension code in shell.c and as an extension to sqlite3.c, it causes no end of issues that require #ifdef'ing out the nasty duplications.

I would suggest that if someone wants to add custom extensions into the core that they do it properly by appending the extension to sqlite3.c and then adding their own SQLITE_EXTRA_INIT function to add those functions (via auto_extension) or loading the modules at sqlite3_initialize time.

**Comment by rogerbinns** [comment]
I only include extenstions that are distributed as part of the SQLite- amalgamation - ie those the SQLite team think broadly apply to everyone.  In the past setup.py was able to download other extensions etc, but that is not worth it any more.

You can use loadextension to load the standard csv extenion.  Also note that the APSW shell includes a handy .autoimport command:

````
sqlite> .help autoimport

.autoimport FILENAME ?TABLE?  Imports filename creating a table and automatically 
working out separators and data types (alternative to .import command)

The import command requires that you precisely pre-setup the table and schema, and 
set the data separators (eg commas or tabs).  In many cases this information can be 
automatically deduced from the file contents which is what this command does.  There 
must be at least two columns and two rows.

If the table is not specified then the basename of the file will be used.

Additionally the type of the contents of each column is also deduced - for example if it is a
number or date.  Empty values are turned into nulls.  Dates are normalized into 
YYYY-MM-DD format and DateTime are normalized into ISO8601 format to allow easy 
sorting and searching.  4 digit years must be used to detect dates.  US (swapped day and
month) versus rest of the world is also detected providing there is at least one value that 
resolves the ambiguity.

Care is taken to ensure that columns looking like numbers are only treated as numbers if 
they do not have unnecessary leading zeroes or plus signs.  This is to avoid treating phone 
numbers and similar number like strings as integers.

This command can take quite some time on large files as they are effectively imported twice.  
The first time is to determine the format and the types for each column while the second pass
 actually imports the data.
````

**Comment by rogerbinns** [comment]
@deecay you'll be pleased to see [apsw.sqlite_extra](https://rogerbinns.github.io/apsw/extra.html) which includes the csv and all the other SQLite extensions and programs.
