### ISSUE TITLE
APSW version for Windows Python 3.6 64bit cannot be installed

### ISSUE THREAD

**Issue by rengel-de** [rogerbinns/apsw#233]
The 64-bit version of APSW (apsw-3.17.0-r1.win-amd64-py3.6.exe, downloaded from https://rogerbinns.github.io/apsw/download.html) cannot be installed. 
I get the error message:

Python version 3.6-32 required, which was not found in the registry.

I'm working with a properly installed 64-bit version of Python. Why should Python 3.6-32 be required?

An alternate way of installing APSW doesn't work either. I get the same CERTIFICATE_VERIFY_FAILED errors as mentioned in post https://github.com/rogerbinns/apsw/issues/231.

**Comment by rogerbinns** [comment]
This is a Python bug and not something I can do anything about:  http://bugs.python.org/issue25148
