### ISSUE TITLE
apsw code completion

### ISSUE THREAD

**Issue by rengel-de** [rogerbinns/apsw#234]
I'm doing my Python programming using the PyCharm IDE. When using apsw, I'm missing the code completion functionality, because the names of the APSW API members are not visible in apsw.py. It would be nice to have access to these names. In the meanwhile I have changed apsw.py so that the names are exported. I'm new to apsw, so I don't know if these are all the names (or too many). I just generated the list by using

`import apsw

members = dir(apsw)

def makeAll(members):
    print('__all__ = [')
    for member in members:
        print("    '%s'," % member)
    print(']')

makeAll(members)
`

With this altered apsw.py the code completion works:

`__all__ = [
    'AbortError',
    'AuthError',
    'BindingsError',
    'BusyError',
    'CantOpenError',
    'Connection',
    'ConnectionClosedError',
    'ConnectionNotClosedError',
    'ConstraintError',
    'CorruptError',
    'CursorClosedError',
    'EmptyError',
    'Error',
    'ExecTraceAbort',
    'ExecutionCompleteError',
    'ExtensionLoadingError',
    'ForkingViolationError',
    'FormatError',
    'FullError',
    'IOError',
    'IncompleteExecutionError',
    'InternalError',
    'InterruptError',
    'LockedError',
    'MismatchError',
    'MisuseError',
    'NoLFSError',
    'NoMemError',
    'NotADBError',
    'NotFoundError',
    'PermissionsError',
    'ProtocolError',
    'RangeError',
    'ReadOnlyError',
    'SQLError',
    'SQLITE_ABORT',
    'SQLITE_ABORT_ROLLBACK',
    'SQLITE_ACCESS_EXISTS',
    'SQLITE_ACCESS_READ',
    'SQLITE_ACCESS_READWRITE',
    'SQLITE_ALTER_TABLE',
    'SQLITE_ANALYZE',
    'SQLITE_ATTACH',
    'SQLITE_AUTH',
    'SQLITE_AUTH_USER',
    'SQLITE_BUSY',
    'SQLITE_BUSY_RECOVERY',
    'SQLITE_BUSY_SNAPSHOT',
    'SQLITE_CANTOPEN',
    'SQLITE_CANTOPEN_CONVPATH',
    'SQLITE_CANTOPEN_FULLPATH',
    'SQLITE_CANTOPEN_ISDIR',
    'SQLITE_CANTOPEN_NOTEMPDIR',
    'SQLITE_CHECKPOINT_FULL',
    'SQLITE_CHECKPOINT_PASSIVE',
    'SQLITE_CHECKPOINT_RESTART',
    'SQLITE_CHECKPOINT_TRUNCATE',
    'SQLITE_CONFIG_COVERING_INDEX_SCAN',
    'SQLITE_CONFIG_GETMALLOC',
    'SQLITE_CONFIG_GETMUTEX',
    'SQLITE_CONFIG_GETPCACHE',
    'SQLITE_CONFIG_GETPCACHE2',
    'SQLITE_CONFIG_HEAP',
    'SQLITE_CONFIG_LOG',
    'SQLITE_CONFIG_LOOKASIDE',
    'SQLITE_CONFIG_MALLOC',
    'SQLITE_CONFIG_MEMSTATUS',
    'SQLITE_CONFIG_MMAP_SIZE',
    'SQLITE_CONFIG_MULTITHREAD',
    'SQLITE_CONFIG_MUTEX',
    'SQLITE_CONFIG_PAGECACHE',
    'SQLITE_CONFIG_PCACHE',
    'SQLITE_CONFIG_PCACHE2',
    'SQLITE_CONFIG_PCACHE_HDRSZ',
    'SQLITE_CONFIG_PMASZ',
    'SQLITE_CONFIG_SCRATCH',
    'SQLITE_CONFIG_SERIALIZED',
    'SQLITE_CONFIG_SINGLETHREAD',
    'SQLITE_CONFIG_SQLLOG',
    'SQLITE_CONFIG_STMTJRNL_SPILL',
    'SQLITE_CONFIG_URI',
    'SQLITE_CONFIG_WIN32_HEAPSIZE',
    'SQLITE_CONSTRAINT',
    'SQLITE_CONSTRAINT_CHECK',
    'SQLITE_CONSTRAINT_COMMITHOOK',
    'SQLITE_CONSTRAINT_FOREIGNKEY',
    'SQLITE_CONSTRAINT_FUNCTION',
    'SQLITE_CONSTRAINT_NOTNULL',
    'SQLITE_CONSTRAINT_PRIMARYKEY',
    'SQLITE_CONSTRAINT_ROWID',
    'SQLITE_CONSTRAINT_TRIGGER',
    'SQLITE_CONSTRAINT_UNIQUE',
    'SQLITE_CONSTRAINT_VTAB',
    'SQLITE_COPY',
    'SQLITE_CORRUPT',
    'SQLITE_CORRUPT_VTAB',
    'SQLITE_CREATE_INDEX',
    'SQLITE_CREATE_TABLE',
    'SQLITE_CREATE_TEMP_INDEX',
    'SQLITE_CREATE_TEMP_TABLE',
    'SQLITE_CREATE_TEMP_TRIGGER',
    'SQLITE_CREATE_TEMP_VIEW',
    'SQLITE_CREATE_TRIGGER',
    'SQLITE_CREATE_VIEW',
    'SQLITE_CREATE_VTABLE',
    'SQLITE_DBCONFIG_ENABLE_FKEY',
    'SQLITE_DBCONFIG_ENABLE_FTS3_TOKENIZER',
    'SQLITE_DBCONFIG_ENABLE_LOAD_EXTENSION',
    'SQLITE_DBCONFIG_ENABLE_TRIGGER',
    'SQLITE_DBCONFIG_LOOKASIDE',
    'SQLITE_DBCONFIG_MAINDBNAME',
    'SQLITE_DBCONFIG_NO_CKPT_ON_CLOSE',
    'SQLITE_DBSTATUS_CACHE_HIT',
    'SQLITE_DBSTATUS_CACHE_MISS',
    'SQLITE_DBSTATUS_CACHE_USED',
    'SQLITE_DBSTATUS_CACHE_USED_SHARED',
    'SQLITE_DBSTATUS_CACHE_WRITE',
    'SQLITE_DBSTATUS_DEFERRED_FKS',
    'SQLITE_DBSTATUS_LOOKASIDE_HIT',
    'SQLITE_DBSTATUS_LOOKASIDE_MISS_FULL',
    'SQLITE_DBSTATUS_LOOKASIDE_MISS_SIZE',
    'SQLITE_DBSTATUS_LOOKASIDE_USED',
    'SQLITE_DBSTATUS_MAX',
    'SQLITE_DBSTATUS_SCHEMA_USED',
    'SQLITE_DBSTATUS_STMT_USED',
    'SQLITE_DELETE',
    'SQLITE_DENY',
    'SQLITE_DETACH',
    'SQLITE_DONE',
    'SQLITE_DROP_INDEX',
    'SQLITE_DROP_TABLE',
    'SQLITE_DROP_TEMP_INDEX',
    'SQLITE_DROP_TEMP_TABLE',
    'SQLITE_DROP_TEMP_TRIGGER',
    'SQLITE_DROP_TEMP_VIEW',
    'SQLITE_DROP_TRIGGER',
    'SQLITE_DROP_VIEW',
    'SQLITE_DROP_VTABLE',
    'SQLITE_EMPTY',
    'SQLITE_ERROR',
    'SQLITE_FAIL',
    'SQLITE_FCNTL_BUSYHANDLER',
    'SQLITE_FCNTL_CHUNK_SIZE',
    'SQLITE_FCNTL_COMMIT_PHASETWO',
    'SQLITE_FCNTL_FILE_POINTER',
    'SQLITE_FCNTL_GET_LOCKPROXYFILE',
    'SQLITE_FCNTL_HAS_MOVED',
    'SQLITE_FCNTL_JOURNAL_POINTER',
    'SQLITE_FCNTL_LAST_ERRNO',
    'SQLITE_FCNTL_LOCKSTATE',
    'SQLITE_FCNTL_MMAP_SIZE',
    'SQLITE_FCNTL_OVERWRITE',
    'SQLITE_FCNTL_PDB',
    'SQLITE_FCNTL_PERSIST_WAL',
    'SQLITE_FCNTL_POWERSAFE_OVERWRITE',
    'SQLITE_FCNTL_PRAGMA',
    'SQLITE_FCNTL_RBU',
    'SQLITE_FCNTL_SET_LOCKPROXYFILE',
    'SQLITE_FCNTL_SIZE_HINT',
    'SQLITE_FCNTL_SYNC',
    'SQLITE_FCNTL_SYNC_OMITTED',
    'SQLITE_FCNTL_TEMPFILENAME',
    'SQLITE_FCNTL_TRACE',
    'SQLITE_FCNTL_VFSNAME',
    'SQLITE_FCNTL_VFS_POINTER',
    'SQLITE_FCNTL_WAL_BLOCK',
    'SQLITE_FCNTL_WIN32_AV_RETRY',
    'SQLITE_FCNTL_WIN32_GET_HANDLE',
    'SQLITE_FCNTL_WIN32_SET_HANDLE',
    'SQLITE_FCNTL_ZIPVFS',
    'SQLITE_FORMAT',
    'SQLITE_FULL',
    'SQLITE_FUNCTION',
    'SQLITE_IGNORE',
    'SQLITE_INDEX_CONSTRAINT_EQ',
    'SQLITE_INDEX_CONSTRAINT_GE',
    'SQLITE_INDEX_CONSTRAINT_GLOB',
    'SQLITE_INDEX_CONSTRAINT_GT',
    'SQLITE_INDEX_CONSTRAINT_LE',
    'SQLITE_INDEX_CONSTRAINT_LIKE',
    'SQLITE_INDEX_CONSTRAINT_LT',
    'SQLITE_INDEX_CONSTRAINT_MATCH',
    'SQLITE_INDEX_CONSTRAINT_REGEXP',
    'SQLITE_INDEX_SCAN_UNIQUE',
    'SQLITE_INSERT',
    'SQLITE_INTERNAL',
    'SQLITE_INTERRUPT',
    'SQLITE_IOCAP_ATOMIC',
    'SQLITE_IOCAP_ATOMIC16K',
    'SQLITE_IOCAP_ATOMIC1K',
    'SQLITE_IOCAP_ATOMIC2K',
    'SQLITE_IOCAP_ATOMIC32K',
    'SQLITE_IOCAP_ATOMIC4K',
    'SQLITE_IOCAP_ATOMIC512',
    'SQLITE_IOCAP_ATOMIC64K',
    'SQLITE_IOCAP_ATOMIC8K',
    'SQLITE_IOCAP_IMMUTABLE',
    'SQLITE_IOCAP_POWERSAFE_OVERWRITE',
    'SQLITE_IOCAP_SAFE_APPEND',
    'SQLITE_IOCAP_SEQUENTIAL',
    'SQLITE_IOCAP_UNDELETABLE_WHEN_OPEN',
    'SQLITE_IOERR',
    'SQLITE_IOERR_ACCESS',
    'SQLITE_IOERR_AUTH',
    'SQLITE_IOERR_BLOCKED',
    'SQLITE_IOERR_CHECKRESERVEDLOCK',
    'SQLITE_IOERR_CLOSE',
    'SQLITE_IOERR_CONVPATH',
    'SQLITE_IOERR_DELETE',
    'SQLITE_IOERR_DELETE_NOENT',
    'SQLITE_IOERR_DIR_CLOSE',
    'SQLITE_IOERR_DIR_FSYNC',
    'SQLITE_IOERR_FSTAT',
    'SQLITE_IOERR_FSYNC',
    'SQLITE_IOERR_GETTEMPPATH',
    'SQLITE_IOERR_LOCK',
    'SQLITE_IOERR_MMAP',
    'SQLITE_IOERR_NOMEM',
    'SQLITE_IOERR_RDLOCK',
    'SQLITE_IOERR_READ',
    'SQLITE_IOERR_SEEK',
    'SQLITE_IOERR_SHMLOCK',
    'SQLITE_IOERR_SHMMAP',
    'SQLITE_IOERR_SHMOPEN',
    'SQLITE_IOERR_SHMSIZE',
    'SQLITE_IOERR_SHORT_READ',
    'SQLITE_IOERR_TRUNCATE',
    'SQLITE_IOERR_UNLOCK',
    'SQLITE_IOERR_VNODE',
    'SQLITE_IOERR_WRITE',
    'SQLITE_LIMIT_ATTACHED',
    'SQLITE_LIMIT_COLUMN',
    'SQLITE_LIMIT_COMPOUND_SELECT',
    'SQLITE_LIMIT_EXPR_DEPTH',
    'SQLITE_LIMIT_FUNCTION_ARG',
    'SQLITE_LIMIT_LENGTH',
    'SQLITE_LIMIT_LIKE_PATTERN_LENGTH',
    'SQLITE_LIMIT_SQL_LENGTH',
    'SQLITE_LIMIT_TRIGGER_DEPTH',
    'SQLITE_LIMIT_VARIABLE_NUMBER',
    'SQLITE_LIMIT_VDBE_OP',
    'SQLITE_LIMIT_WORKER_THREADS',
    'SQLITE_LOCKED',
    'SQLITE_LOCKED_SHAREDCACHE',
    'SQLITE_LOCK_EXCLUSIVE',
    'SQLITE_LOCK_NONE',
    'SQLITE_LOCK_PENDING',
    'SQLITE_LOCK_RESERVED',
    'SQLITE_LOCK_SHARED',
    'SQLITE_MISMATCH',
    'SQLITE_MISUSE',
    'SQLITE_NOLFS',
    'SQLITE_NOMEM',
    'SQLITE_NOTADB',
    'SQLITE_NOTFOUND',
    'SQLITE_NOTICE',
    'SQLITE_NOTICE_RECOVER_ROLLBACK',
    'SQLITE_NOTICE_RECOVER_WAL',
    'SQLITE_OK',
    'SQLITE_OK_LOAD_PERMANENTLY',
    'SQLITE_OPEN_AUTOPROXY',
    'SQLITE_OPEN_CREATE',
    'SQLITE_OPEN_DELETEONCLOSE',
    'SQLITE_OPEN_EXCLUSIVE',
    'SQLITE_OPEN_FULLMUTEX',
    'SQLITE_OPEN_MAIN_DB',
    'SQLITE_OPEN_MAIN_JOURNAL',
    'SQLITE_OPEN_MASTER_JOURNAL',
    'SQLITE_OPEN_MEMORY',
    'SQLITE_OPEN_NOMUTEX',
    'SQLITE_OPEN_PRIVATECACHE',
    'SQLITE_OPEN_READONLY',
    'SQLITE_OPEN_READWRITE',
    'SQLITE_OPEN_SHAREDCACHE',
    'SQLITE_OPEN_SUBJOURNAL',
    'SQLITE_OPEN_TEMP_DB',
    'SQLITE_OPEN_TEMP_JOURNAL',
    'SQLITE_OPEN_TRANSIENT_DB',
    'SQLITE_OPEN_URI',
    'SQLITE_OPEN_WAL',
    'SQLITE_PERM',
    'SQLITE_PRAGMA',
    'SQLITE_PROTOCOL',
    'SQLITE_RANGE',
    'SQLITE_READ',
    'SQLITE_READONLY',
    'SQLITE_READONLY_CANTLOCK',
    'SQLITE_READONLY_DBMOVED',
    'SQLITE_READONLY_RECOVERY',
    'SQLITE_READONLY_ROLLBACK',
    'SQLITE_RECURSIVE',
    'SQLITE_REINDEX',
    'SQLITE_REPLACE',
    'SQLITE_ROLLBACK',
    'SQLITE_ROW',
    'SQLITE_SAVEPOINT',
    'SQLITE_SCHEMA',
    'SQLITE_SELECT',
    'SQLITE_SHM_EXCLUSIVE',
    'SQLITE_SHM_LOCK',
    'SQLITE_SHM_SHARED',
    'SQLITE_SHM_UNLOCK',
    'SQLITE_STATUS_MALLOC_COUNT',
    'SQLITE_STATUS_MALLOC_SIZE',
    'SQLITE_STATUS_MEMORY_USED',
    'SQLITE_STATUS_PAGECACHE_OVERFLOW',
    'SQLITE_STATUS_PAGECACHE_SIZE',
    'SQLITE_STATUS_PAGECACHE_USED',
    'SQLITE_STATUS_PARSER_STACK',
    'SQLITE_STATUS_SCRATCH_OVERFLOW',
    'SQLITE_STATUS_SCRATCH_SIZE',
    'SQLITE_STATUS_SCRATCH_USED',
    'SQLITE_SYNC_DATAONLY',
    'SQLITE_SYNC_FULL',
    'SQLITE_SYNC_NORMAL',
    'SQLITE_TOOBIG',
    'SQLITE_TRANSACTION',
    'SQLITE_UPDATE',
    'SQLITE_VERSION_NUMBER',
    'SQLITE_VTAB_CONSTRAINT_SUPPORT',
    'SQLITE_WARNING',
    'SQLITE_WARNING_AUTOINDEX',
    'SchemaChangeError',
    'Shell',
    'ThreadingViolationError',
    'TooBigError',
    'URIFilename',
    'VFS',
    'VFSFile',
    'VFSFileClosedError',
    'VFSNotImplementedError',
    '__builtins__',
    '__doc__',
    '__file__',
    '__loader__',
    '__name__',
    '__package__',
    '__spec__',
    '_win_colour',
    'apsw',
    'apswversion',
    'base64',
    'codecs',
    'compile_options',
    'complete',
    'config',
    'connection_hooks',
    'csv',
    'enablesharedcache',
    'exceptionfor',
    'format_sql_value',
    'initialize',
    'log',
    'main',
    'mapping_access',
    'mapping_authorizer_function',
    'mapping_authorizer_return',
    'mapping_bestindex_constraints',
    'mapping_config',
    'mapping_conflict_resolution_modes',
    'mapping_db_config',
    'mapping_db_status',
    'mapping_device_characteristics',
    'mapping_extended_result_codes',
    'mapping_file_control',
    'mapping_limits',
    'mapping_locking_level',
    'mapping_open_flags',
    'mapping_result_codes',
    'mapping_status',
    'mapping_sync',
    'mapping_virtual_table_configuration_options',
    'mapping_virtual_table_scan_flags',
    'mapping_wal_checkpoint',
    'mapping_xshmlock_flags',
    'memoryhighwater',
    'memoryused',
    'os',
    'randomness',
    're',
    'releasememory',
    'shlex',
    'shutdown',
    'softheaplimit',
    'sqlite3_sourceid',
    'sqlitelibversion',
    'status',
    'sys',
    'textwrap',
    'time',
    'using_amalgamation',
    'vfsnames',
    'zeroblob',
]

def __bootstrap__():
    global __bootstrap__, __loader__, __file__
    import sys, pkg_resources, imp
    __file__ = pkg_resources.resource_filename(__name__, 'apsw.cp36-win_amd64.pyd')
    __loader__ = None; del __bootstrap__, __loader__
    imp.load_dynamic(__name__,__file__)
__bootstrap__()
`
(This editor seems to destroy the correct Python indentation.)

**Comment by rogerbinns** [comment]
There is no apsw.py - APSW is an extension module (.so/.pyd or equivalent) only.  pycharm is the problem here.  If there is something specific that can be updated then I am happy to do so.
