### ISSUE TITLE
enableloadextension error

### ISSUE THREAD

**Issue by rengel-de** [rogerbinns/apsw#235]
Why I'm getting this error?
![apsw-error](https://cloud.githubusercontent.com/assets/2276455/23946274/1349a082-097a-11e7-8c44-245d7c80e8e2.png)

I downloaded the latest aspw-master.zip file Git and the latest sqlite amalgamation file (sqlite-amalgamation-3170000.zip) from Git. Then I unzipped aspw-master file to an installation directory. There I created a subdirectory and unzipped the sqlite file into it. After that I build and installed apsw locally using the following command:
python setup.py build --enable-all-extensions install test
Everything (including the tests) was executed without a glitch.
But then I got the error shown above.
Alternately I tried using the sqlite3.dll (from sqlite-dll-win64-x64-3170000.zip) in the sqlite3 subdirectory, but got the same error.
Using 'python setup.py build_ext' didn't help either.
Even using '--enable=load_extension' didn't help.

**Comment by rogerbinns** [comment]
Please don't use apsw-master from github unless you are doing apsw development itself.  (It is very annoying that github keep encouraging people to download that instead of the actual release - I've repeatedly asked them to fix this but they won't.)

This should be working for you - extension loading is only omitted when SQLITE_OMIT_LOAD_EXTENSION is defined.

**Comment by dunha** [comment]
I'm also having problems loading an extension
apsw,  extension and dependencies are all in the same folder and all 64 bit

`>>> import apsw
>>> con = apsw.Connection(':memory:')
>>> con.enableloadextension(True)
>>> con.loadextension('mod_spatialite')
Traceback (most recent call last):
  File "<string>", line 301, in runcode
  File "<interactive input>", line 1, in <module>
apsw.ExtensionLoadingError: ExtensionLoadingError: A dynamic link library (DLL) initialization routine failed.`

**Comment by rogerbinns** [comment]
@dunha your issue has nothing to do with this ticket, or apsw itself.  apsw makes one function call to sqlite which either succeeds or fails.  When it fails the message from sqlite is included in the exception.

You'll need to figure out the issue with your extension - which could be the initialization routine failing as sqlite states or something you need to figure out using appropriate tools for your platform such as dependency walker and process explorer for Windows.
