### ISSUE TITLE
Inserting into 2G sqlite file gives apsw.FullError but works ok from commandline client

### ISSUE THREAD

**Issue by bakert** [rogerbinns/apsw#237]
Steps to repro:

- Get a 2G sqlite db.
- Attempt to insert some more data from python using apsw.

Expected:

- Works fine as a sqlite db can be up to 140TB.

Actual:

    Traceback (most recent call last):
      File "../Penny-Dreadful-Discord-Bot/run.py", line 54, in <module>
        run()
      File "../Penny-Dreadful-Discord-Bot/run.py", line 19, in run
        price_grabber.price.cache()
      File "/home/discord/Penny-Dreadful-Discord-Bot/price_grabber/price.py", line 58, in cache
        conn.cursor().execute(sql, [latest, week, week, month, month, last_rotation, last_rotation, last_rotation])
      File "src/cursor.c", line 236, in resetcursor
    apsw.FullError: FullError: database or disk is full

Could this be an issue in apsw? The 2G made me think of 32-bit limits but I've verified this is happening in 64-bit python.

**Comment by bakert** [comment]
I copied the database to my Mac (it's running on OpenSUSE) and I can insert into it at 3.9G and beyond so it's something to do with the server. 

I can also insert into this db from the python interpreting using apsw so I suppose this probably isn't apsw related. I'll close this out but feel free to add any hints if you have any!

**Comment by rogerbinns** [comment]
As you noted, SQLite and APSW work just fine with multi-gigabyte databases.  What you did experience is that virtually any error SQLite encouters while writing is translated into the disk full error.

If you get SQLite detailed logging - https://rogerbinns.github.io/apsw/tips.html#diagnostics - then you'll get an idea of what actually happened.

**Comment by bakert** [comment]
Thanks for the tip. I don't suppose this is any clearer to you than it is to me?

    SQLITE_LOG: statement aborts at 62: [
            INSERT INTO cache (`time`, name, price, low, high, week, month, season)
                SELECT
                    MAX(`time`) AS `time`,
                    name,
                    MIN(CAS (13) SQLITE_FULL
    Traceback (most recent call last):
      File "../Penny-Dreadful-Discord-Bot/run.py", line 54, in <module>
        run()
      File "../Penny-Dreadful-Discord-Bot/run.py", line 19, in run
        price_grabber.price.cache()
      File "/home/discord/Penny-Dreadful-Discord-Bot/price_grabber/price.py", line 58, in cache
        conn.cursor().execute(sql, [latest, week, week, month, month, last_rotation, last_rotation, last_rotation])
      File "src/cursor.c", line 236, in resetcursor
    apsw.FullError: FullError: database or disk is full
