### ISSUE TITLE
allow getting description for empty query result

### ISSUE THREAD

**Issue by pluspku** [rogerbinns/apsw#238]
Hi,

I recently ran in problem when query returns no result, the cur.description won't work. e.g.
```
cur.execute("select 1 where 0")
cur.description
```
and got exception "Can't get description for statements that have completed execution"
I understand that apsw is implemented in a highly optimized way, but is it possible to add support to return column names in all cases? This would be very useful, otherwise I have to parse sql by myself to know what the columns would be in case of empty result.

Thank you in advance.

**Comment by rogerbinns** [comment]
I tried in the past but it was a fair bit of work and negatively affected performance.  Currently the description is calculated on demand only when it is asked for.  To get the above to work, it would have to always create and store the description just _in case_ it is asked for after the query completes.

It should also be noted that retroactively getting column names is not considered best practise.  Instead the columns desired should be explicitly requested and named.
