### ISSUE TITLE
apsw is created as file based egg (zip_safe not set)

### ISSUE THREAD

**Issue by stuertz** [rogerbinns/apsw#243]
Hi, 
I just wanted to build apsw 3.21.0-r1 from tar.gz with setuptools 36.7.2
The build created a .egg File and not a folder, so that the apsw.pyd can't be found.

After patching setup.py to call setup() with zip_safe=False, I got an egg Folder, and the apsw.so | apsw.pyd file was found inside of that folder after restarting the python interpreter.

What currently understandably does not work is to run 
`setup.py install test`
in one step in this scenario.

I think most of the cause came from the new setuptools version, and I will open a parallel issue there. 
But it may be a good idea to set zip_safe explicitly to false inside of apsw.

**Comment by rogerbinns** [comment]
Based on http://setuptools.readthedocs.io/en/latest/setuptools.html#setting-the-zip-safe-flag setuptools should be doing the right thing.  They claim "extremely conservative", "any C extensions" etc.  apsw is *only* a C extension, so setuptools should be getting this right.

**Comment by stuertz** [comment]
agreed. Seemed they got away from from their claim :-( .
see also https://github.com/pypa/setuptools/issues/1199

**Comment by rogerbinns** [comment]
Closing because this isn't an APSW issue and adding the flag then breaks install test etc.
