### ISSUE TITLE
Minor typo?

### ISSUE THREAD

**Issue by pl77** [rogerbinns/apsw#247]
Not sure if this is a typo, but when I was looking through the source of setup.py for something else I noticed on line 98 it said: 
``` 
if ver>=3120000:
    year="2018"
```
Should that be `if ver>= 3210000`?

https://github.com/rogerbinns/apsw/blob/a6d07d526a25df677fc1d7df63dd385cc6b294d6/setup.py#L79

**Comment by rogerbinns** [comment]
Thank you for spotting that.  Not only are the digits transposed, they should have corresponded to this release (3.22 not 3.21).

Fortunately it doesn't really make any difference since APSW typically only supports the most recent release.
