### ISSUE TITLE
Installation with pipenv

### ISSUE THREAD

**Issue by cLupus** [rogerbinns/apsw#248]
Hi,
Do you have a suggested way of installing apse with [pipenv](https://docs.pipenv.org)?

I have tried with

```
PIP_INSTALL_OPTIONS="fetch --version 3.22.0 --all build --enable-all-extensions tests" pipenv install https://github.com/rogerbinns/apsw/releases/download/3.22.0-r1/apsw-3.22.0-r1.zip
```

Wich, kind of, works, though SQLite was not downloaded, and the plugins seem to have been downloaded. That is, the tests are successful, and I am able to query JSON data.

There will then be a reference to the zip file in `Pipefile`, but without any references to installation options.

**Comment by rogerbinns** [comment]
Sorry I have no idea about pipenv.  In general the problem with pip and friends is that they do not provide a way of specifying options like you did.  I do not know of workarounds.

That said you do not need to build apsw in one of those environments.  You can build outside pip (using whatever options you want) and copy the single resulting apsw.so file wherever you want inside the pipenvs.
