### ISSUE TITLE
Calling RBU extension functions?

### ISSUE THREAD

**Issue by rcoup** [rogerbinns/apsw#251]
https://www.sqlite.org/rbu.html describes the key RBU extension functions (`sqlite3rbu_*`), and the full set is in https://sqlite.org/src/doc/trunk/ext/rbu/sqlite3rbu.h

While APSW allows me to build sqlite with the RBU extension included, is there a way to actually call the RBU functions?

**Comment by rogerbinns** [comment]
You are correct.   I thought the SQL level stuff would be sufficient while adding, but at the end discovered that it can't be used at all without them.  Doing this is on the list, but will take a while.  (The time goes on documentation, testing, error handling etc.)
