### ISSUE TITLE
Please add info about installing and compiling

### ISSUE THREAD

**Issue by E3V3A** [rogerbinns/apsw#252]
Hi Roger! 
Great project and surely a lot of effort!
But please add some more info on the README page regarding installation, compilation, version compatibility etc. Perhaps more people can help you out with maintenance and adding new features etc. 
Cheers,
E:V:A

**Comment by rogerbinns** [comment]
The readme already directly includes or points to the information you requested.  I could make the readme longer and duplicate information from the doc, but that generally doesn't help.
