### ISSUE TITLE
Versioning scheme "-r1" does not follow setuptools guidelines

### ISSUE THREAD

**Issue by eblume** [rogerbinns/apsw#254]
Currently, the python project management tool `poetry` (https://github.com/sdispater/poetry) has trouble installing `apsw` due to the versioning scheme you've used (`-r1`), as in `3.9.2-r1`. I have filed a bug with poetry to support your versioning scheme, here: https://github.com/sdispater/poetry/issues/656

I understand that you might not want to change your versioning scheme to fit a third party project (that would be unreasonable), however I wanted to let you know that your chosen scheme clashes with the setuptools standard ( https://setuptools.readthedocs.io/en/latest/setuptools.html#specifying-your-project-s-version ) in that the standard expects "-rc1", not "-r1". A small issue, but one I just stumbled on.

Thanks!

**Comment by rogerbinns** [comment]
Note that the -r1 is a release, not a release candidate.  The versioning scheme used is borrowed from gentoo when this project started 14 years ago - ie upstream release version dash 'r' downstream corresponding release.

I haven't been able to find a better scheme in all this time.  SQLite uses up to 4 dot separated numbers so I would have to use 5 which is also rejected by various tools.  

If anyone can figure out a better scheme that:

* Includes SQLite release
* Includes a corresponding APSW release version
* Keeps all the tools and their requirements happy

Then I'll happily switch.  So far other projects found it easier to just accommodate what APSW does.
