### ISSUE TITLE
APSWBuffer_FromObject() "conniving performance hack" is unreliable

### ISSUE THREAD

**Issue by dgrunwald** [rogerbinns/apsw#256]
`Assertion failed: tmp==APSWBuffer_hash(res), file apsw\src\apswbuffer.c, line 200`

Using APSW 3.26.0-r1 on Python 2.7.15 on Windows.
When using `PYTHONHASHSEED=random`, `APSWBuffer_hash()` no longer corresponds to Python hash algorithm, which invalidates the optimization of stealing the existing hash code.
In debug mode this triggers an assertion, not sure what kind of misbehavior could be triggered in normal builds.

Hash Randomization is enabled by default in Python 3, so that's probably also affected.

**Comment by rogerbinns** [comment]
I greatly appreciate you finding this problem - thank you!
