### ISSUE TITLE
-lmsvcr140

### ISSUE THREAD

**Issue by karelv** [rogerbinns/apsw#257]
I tried to compile it with mingw gcc 8.1.0.
I used the command:
`python setup.py build --compile=mingw32 install`

This works, but the linking as shared does not find `-lmsvcr140`.

I do the linking command line by hand, after removing that library.
So my question is then is `msvcr140` a required lib, when compiling with mingw?

**Comment by rogerbinns** [comment]
Unless you are experienced in mingw, I recommend you install and use [Microsoft compilers instead](https://wiki.python.org/moin/WindowsCompilers).
