### ISSUE TITLE
How to set an environmental variable to apsw before starting python

### ISSUE THREAD

**Issue by ValeryPolyakov** [rogerbinns/apsw#262]
apsw was installed on my machine, but "import apsw" is not working in python interpreter:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'apsw'

How do I set an environmental variable to the package in Linux 6?

Thanks.

**Comment by rogerbinns** [comment]
In Linux you set environment variables in the shell.  For example in bash ````name=value```` and ````export name````.  You can also set them just for a command using env such as ````env name=value python myscript.py````
