### ISSUE TITLE
lsm1 extension won't load

### ISSUE THREAD

**Issue by ingoogni** [rogerbinns/apsw#265]
Does the lsm1 extension work with apsw? Or is the problem on my side?

On Win10, when loading the lsm1 extension I get the following error:
```
Traceback (most recent call last):
  File "OBY.py", line 142, in <module>
    connection.loadextension(r'lsm')
apsw.ExtensionLoadingError: ExtensionLoadingError: Kan opgegeven procedure niet vinden. (can't find the procedure)
```
compiled on Win10 with Mingwin64 by adding sqlite3.h and sqlite3ext.h to the lsm1 directory and then: make ```lsm.so TCCX="gcc -g -O2"``` and rename to dll.

Other extensions are loaded fine and from the same location.
The lsm.dll works fine from the sqlite shell.

**Comment by rogerbinns** [comment]
That is an error in the extension - it isn't exposing the initialisation routine.  The error message is coming from SQLite.  SQLite does make various attempts to look at other file and function names - see the [doc](https://sqlite.org/c3ref/load_extension.html)
