### ISSUE TITLE
Test failures with sqlite 3.30

### ISSUE THREAD

**Issue by eli-schwartz** [rogerbinns/apsw#275]
Attempting to build the latest release of apsw for Arch Linux I hit the following test failure:

```
==> Starting check()...
running test
                Python /usr/bin/python sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)
Testing with APSW file /build/python-apsw/src/apsw-3.28.0-r1/build/lib.linux-x86_64-3.7/apsw.cpython-37m-x86_64-linux-gnu.so
          APSW version 3.28.0-r1
    SQLite lib version 3.30.0
SQLite headers version 3030000
    Using amalgamation False
Not doing LoadExtension test.  You need to compile the extension first
  gcc -fPIC -shared -o ./testextension.sqlext -I. -Isqlite3 src/testextension.c
...............................................................................F.......
======================================================================
FAIL: testVtables (tests.APSW)
Test virtual table functionality
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-apsw/src/apsw-3.28.0-r1/tests.py", line 2162, in testVtables
    self.assertRaises(apsw.MisuseError, self.db.createmodule, "x"*ii, lambda x: ii)
AssertionError: MisuseError not raised by createmodule

----------------------------------------------------------------------
Ran 87 tests in 999.575s

FAILED (failures=1)
```

I was able to reproduce this on the previous release too, and then narrowed it down to the system upgrade of sqlite from 3.29 to 3.30 -- if I  try downgrading that package, apsw successfully builds.

EDIT: report might be a bit confusing, since I said I tried building the new release, and "also got errors for the old release", but the posted error message is from apsw-3.28.0-r1 -- so, I did test both, and then copy-pasted the old version's error message. Well, I'm sure you get my meaning either way. :D

**Comment by rogerbinns** [comment]
There are no current test failures.

**Comment by eli-schwartz** [comment]
(context: 13df0b57bff59542978abf7c0a440c9274e3aac3)

Thanks for the fix!

**Comment by eli-schwartz** [comment]
@rogerbinns is there any current holdup on cutting a new release for 3.30.0?
