### ISSUE TITLE
Post install test run time

### ISSUE THREAD

**Issue by leung-d** [rogerbinns/apsw#276]
Yesterday I installed apsw on a Mac mini, core 2 duo running Ubuntu 18.04, test took ...
APSW version 3.29.0-r1
SQLite lib version 3.29.0
SQLite headers version 3029000
Using amalgamation True
Ran 87 tests in 444.983s
Ran 88 tests in 569.662s

Today on a white MacBook, also core 2 duo running Ubuntu 18.04, test took ...
Ran 87 tests in 487.587s
Ran 88 tests in 634.163s

I also have a Raspberry Pi 3B+ which I re-run post install test as below ...
          APSW version 3.27.2-r1
    SQLite lib version 3.27.2
SQLite headers version 3027002
    Using amalgamation True
Ran 87 tests in 196.787s
Ran 88 tests in 236.920s

A raspberry pi took less than half the time to run the test! That seem very strange to me. Does anybody have any thoughts on it?

**Comment by rogerbinns** [comment]
Test performance is most influenced by how long the [fsync](https://en.wikipedia.org/wiki/Sync_(Unix)) call takes, waiting for data be durably on storage.

Your Pi either has faster storage, or something in the storage path is saying data is durable before it really is.

You can get best performance using [tmpfs](https://en.wikipedia.org/wiki/Tmpfs).  Set the environment variable APSWTESTPREFIX to put test databases somewhere else.  eg `env APSWTESTPREFIX=/tmp/ python3 tests.py`

No change needed in apsw so closing.
