### ISSUE TITLE
AttributeError: Can't pickle local object 'APSW.testzzForkChecker.<locals>.childtest'

### ISSUE THREAD

**Issue by AUsernameWhichIsNotTaken** [rogerbinns/apsw#277]
Thank you for this great library!

running

/Users/thebox/.pyenv/versions/3.8.0/bin/python3 setup.py fetch --all build --enable-all-extensions test

on Mac OS 10.15.1 didn't test at all first because it couldn't find the library which I found in

cp build/lib.macosx-10.15-x86_64-3.8/apsw.cpython-38-darwin.so ./apsw.so

Running the tests then led to the above error.  It also says

> Not doing LoadExtension test.  You need to compile the extension first

I would have assumed --enable-all-extensions would trigger this?

Here the complete output of the test-run:

<pre>
[I] ⋊> ~/D/apsw-3.30.1-r1 ~/.pyenv/versions/3.8.0/bin/python3 tests.py  08:57:34
                Python /Users/thebox/.pyenv/versions/3.8.0/bin/python3 sys.version_info(major=3, minor=8, micro=0, releaselevel='final', serial=0)
Testing with APSW file /Users/thebox/Downloads/apsw-3.30.1-r1/apsw.so
          APSW version 3.30.1-r1
    SQLite lib version 3.30.1
SQLite headers version 3030001
    Using amalgamation True
Not doing LoadExtension test.  You need to compile the extension first
  gcc -fPIC -bundle -o ./testextension.sqlext -I. -Isqlite3 src/testextension.c
.............................................................../Users/thebox/.pyenv/versions/3.8.0/lib/python3.8/codecs.py:905: DeprecationWarning: 'U' mode is deprecated
  file = builtins.open(filename, mode, buffering)
<string>:1: DeprecationWarning: invalid escape sequence \i
<string>:1466: ResourceWarning: unclosed file <_io.BufferedReader name='test-shell-1'>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
<string>:1614: ResourceWarning: unclosed file <_io.BufferedReader name='test-shell-1'>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
<string>:698: ResourceWarning: unclosed file <_io.BufferedReader name='test-shell-1'>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
<string>:1949: ResourceWarning: unclosed file <_io.TextIOWrapper name='test-shell-1.py' mode='r' encoding='UTF-8'>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
.......................E
======================================================================
ERROR: testzzForkChecker (__main__.APSW)
Test detection of using objects across fork
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 8487, in testzzForkChecker
    p.start()
  File "/Users/thebox/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/thebox/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/thebox/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/Users/thebox/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/thebox/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/thebox/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/thebox/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'APSW.testzzForkChecker.&lt;locals&gt;.childtest'

----------------------------------------------------------------------
Ran 87 tests in 101.080s

FAILED (errors=1)
</pre>

**Comment by AUsernameWhichIsNotTaken** [comment]
I'm sorry I overlooked:

gcc -fPIC -bundle -o ./testextension.sqlext -I. -Isqlite3 src/testextension.c

so 'Not doing LoadExtension test. You need to compile the extension first'
is solved.

**Comment by stuertz** [comment]
Maybe a side effect of changes of the pickle module with Py38. With Python 3.7 everything seems to be fine. Other Question is why this occurs only on Mac.

OTOH: https://docs.python.org/3/library/pickle.html#what-can-be-pickled-and-unpickled says that instance methods can not be pickled at all.

**Comment by rogerbinns** [comment]
This is not reproducable for me on any platform.  Are you sure you don't have some kind of crash checker/analytics that catches the exception and tries to log it?

**Comment by AUsernameWhichIsNotTaken** [comment]
On Sat, 29 Feb 2020 11:14:44 -0800
Roger Binns <notifications@github.com> wrote:

> This is not reproducable for me on any platform.  Are you sure you don't have some kind of crash checker/analytics that catches the exception and tries to log it?

I haven't set up anything like this, e.g. not that I'm aware of, 

best regards Stephan

--
Stephan Lukits <stephan.lukits@gmail.com>

**Comment by felixscheinost** [comment]
This is reproducible using Nix on macOS: `nix-shell -p 'python38.withPackages (ps: with ps; [ apsw ])'`

**Comment by rogerbinns** [comment]
I have no idea why it is trying to pickle that. The test opens the SQLite database in the main process, then does a fork, and then in the child it runs the childtest method which calls various APIs and verifies it gets a forking exception for each one.  (This helps you find unintentional SQLite FAQ q6: Under Unix, you should not carry an open SQLite database across a fork() system call into the child process.)

Note that multiprocessing is used to test fork since that is the most likely way someone would unintentionally do it.  Maybe whatever Python 3.8 you are using is doing something else, such as how Windows does it by re-executing the process?
