### ISSUE TITLE
PyUnicode_FromUnicode is deprecated.

### ISSUE THREAD

**Issue by methane** [rogerbinns/apsw#288]
PyUnicode_FromUnicode is deprecated since Python 3.3.
We are planning to remove it in Python 3.11.

```
./apsw-3.9.2-r1/src/apsw.c:1053:      unires=PyUnicode_FromUnicode(NULL, PyUnicode_GET_SIZE(value)+2);
./apsw-3.9.2-r1/src/apsw.c:1120:            unires=PyUnicode_FromUnicode(NULL, buflen*2+3),
./apsw-3.9.2-r1/src/pyutil.c:246:          PyObject *res=PyUnicode_FromUnicode(NULL, size);
```

**Comment by rogerbinns** [comment]
I am not removing the two other occurrences until forced by the API actually going away (ie compile errors).  I have spent enough time on this already. 

The logical and documented thing to do would be to use PyUnicode_New but that is documented as being non-resizeable.  Resizing is needed in the code,  figuring out some other path through the API functions failed.

**Comment by methane** [comment]
PyUnicode_DecodeUTF8 has a fast path [1] for ASCII string, and creating unicode from Py_UNICODE is slow since Python 3.3.
So please don't use this "optimization" for Python 3.

[1] https://github.com/python/cpython/blob/e0bec69854ff17b1a6db9bc01db8c002761bb7a8/Objects/unicodeobject.c#L4993-L5001

**Comment by rogerbinns** [comment]
For clarity, APSW now only uses current APIs with no deprecated API usage.
