### ISSUE TITLE
Some SQLITE_INDEX_CONSTRAINT_* values are not defined in apsw

### ISSUE THREAD

**Issue by scottee** [rogerbinns/apsw#289]
I'm using apsw 3.9.2.post1.

I'm trying to use constraints on virtual tables. But I get this exception:

    AttributeError: module 'apsw' has no attribute 'SQLITE_INDEX_CONSTRAINT_NE'

It looks like most of the constraints are missing from python even thought they're in the .c code.

**Comment by rogerbinns** [comment]
Those constants were added in SQLIite 3.21.0 in October 2017.

Version 3.9.2 is from November 2015 so it won't have the constants.
