### ISSUE TITLE
Please update for SQLite 3.33

### ISSUE THREAD

**Issue by iamthad** [rogerbinns/apsw#291]
[SQLite 3.33.0](https://sqlite.org/releaselog/3_33_0.html) was released on 2020-08-14.

**Comment by rogerbinns** [comment]
The 3.33 update will happen soon enough :-)  The delay is intentional because there is almost always a .1 point release within 10 days and often more point releases.  See [the SQlite chronology](https://sqlite.org/chronology.html).  Is there a reason you want it sooner?

**Comment by iamthad** [comment]
No need for it sooner, thanks. I opened the issue for awareness, and am happy to wait for the likely point release.
