### ISSUE TITLE
Expose sqlite3_create_window_function

### ISSUE THREAD

**Issue by garyhurtz** [rogerbinns/apsw#292]
I was looking to implement a custom (Python) window function, but it doesn't look like APSW exposes sqlite3_create_window_function. Any chance we can get this in an upcoming release?

**Comment by garyhurtz** [comment]
Thanks Roger. Like many, I appreciate your effort developing and maintaining this.

In case it helps, while investigating I came across similar pysqlite open issues [40617](https://bugs.python.org/issue40617) and [34916](https://bugs.python.org/issue34916).

**Comment by rogerbinns** [comment]
Complete - wil be released in 3.40.1.0
