### ISSUE TITLE
using flags=apsw.SQLITE_OPEN_URI giving error

### ISSUE THREAD

**Issue by airen1986** [rogerbinns/apsw#296]
Hi,

I am trying to open db as URI with below code:
conn = apsw.Connection(db_name, flags=apsw.SQLITE_OPEN_URI)

It is giving error:
apsw.MisuseError: MisuseError: bad parameter or other API misuse

Can you please check? Thanks

**Comment by rogerbinns** [comment]
The error is coming from SQLite. You only specified the OPEN_URI flag and no others.  For example if the database does not exist then you'll get the error.  If you add ````apsw.SQLITE_OPEN_CREATE | apsw.SQLITE_OPEN_READWRITE```` to the flags then it opens just fine.
