### ISSUE TITLE
Help with incremental blob insert

### ISSUE THREAD

**Issue by bozhinov** [rogerbinns/apsw#297]
Hello,

I have a backup "software" that I m working on

it is zipping and encrypting files then storing them in a sqlite db

I would very much like to use the blob class to do store my yields as they come. 
The goal is to keep the memory footprint low.
My problem is there is no way to determine the size of the final blob in advance.

I guess this is a limitation of sqlite ?

P.S. now that I think about it..  it is a flat file db. so zeroing it up front makes much sense.

Momchil

**Comment by rogerbinns** [comment]
Yes it is a SQLite limitation.  Note however that blob sizes have nothing do with memory consumption unless you access them in their entirety.  https://rogerbinns.github.io/apsw/blob.html#blob-class

**Comment by bozhinov** [comment]
I  m storing them piece by piece that's why I can't determine the size of the final blob in advance.
so I m ok in terms of consumed memory.
Anyway, it is what it is
