### ISSUE TITLE
Unusual memory spike

### ISSUE THREAD

**Issue by bozhinov** [rogerbinns/apsw#298]
Hello,

I have a very simple piece of code:

import apsw
file = "BLABLABLABLBLA_sql.bak"
db = apsw.Connection('generic.bckp')
cursor = db.cursor()
cursor.execute('CREATE TABLE t (id INTEGER PRIMARY KEY, b BLOB, p BLOB)')
cursor.execute('INSERT INTO {} VALUES(?, ?, ?)'.format("t"), [1, apsw.zeroblob(100256716), file.encode()])

Profiling this results in:
FUNC __main__.__init__ 16.4336 1603143745.8947 17.2578 1603143745.8947 0
FUNC __main__.store_big_file_to 17.2578 1603143745.8947 18.8047 1603143746.4509 0
CMDLINE c:\pyx64\python.exe backup.store.py
MEM 0.566406 1603143745.6557
MEM 10.464844 1603143745.7684
MEM 16.574219 1603143745.8790
**MEM 140.218750 1603143745.9833
MEM 210.031250 1603143746.0890
MEM 210.031250 1603143746.1984
MEM 210.031250 1603143746.3092**
MEM 18.804688 1603143746.4197

Now, if I m to replace file.encode() with b'' this spike goes away

**Comment by rogerbinns** [comment]
This doesn't appear to be an apsw issue.  I recommend the [python-sqlite group](https://groups.google.com/g/python-sqlite?pli=1) for general enquiries.

There will be a memory difference between inserting a zero length blob and a non-zero blob.  The latter occupies more python memory, and also causes SQLite to allocate storage, use its cache etc.  The [gc module](https://docs.python.org/3/library/gc.html) lets you find out about Python memory usage, and there is a [good SQLite page too](https://www.sqlite.org/malloc.html)

**Comment by bozhinov** [comment]
file in my is a string that's like 50 chars .. 
OK . if you recommend the group. sure.
