### ISSUE TITLE
Windows installer didn't find Python directory

### ISSUE THREAD

**Issue by nelson2005** [rogerbinns/apsw#302]
I'm having a bit of trouble with the installer... I'm using apsw-3.33.0-r1.win-amd64-py3.7.exe, and Python is simply in a directory (not 'installed') so the installer cannot find the python installation to use.  Setup halts with a dialog that says "Python 3.7 is required for this package. Select installation to use:" over a selection box, but the box (unsurprisingly) isn't populated and I didn't find a way to manually enter the location of my python exe.

Am I missing something?  Does the package require usage of the Windows registry?

**Comment by rogerbinns** [comment]
The exe does need the registry (aka python installed on the system)  The good news is that the next apsw version (coming out in the next 24 hours or so) includes wheels.  This is what the doc will look like:

![Screenshot_2020-12-17_12-12-55](https://user-images.githubusercontent.com/553885/102538633-637bdf80-4061-11eb-8736-485202dccd1a.png)

**Comment by nelson2005** [comment]
Outstanding, thanks much!
