### ISSUE TITLE
Python 3.9

### ISSUE THREAD

**Issue by kmedcalf** [rogerbinns/apsw#303]
Roger, I had to make the following patch to your setup.py to get the compilation to work properly on Python 3.9.1 (and probably on 3.9 too, but I decided to wait for the first patch version to further debug the problem).

```
Index: setup.py
==================================================================
--- setup.py
+++ setup.py
@@ -615,11 +615,11 @@
         # SQLite 3
         # Look for amalgamation in our directory or in sqlite3 subdirectory

         path = findamalgamation()
         if path:
-            if sys.platform == "win32":
+            if sys.platform == "win32" and sys.version_info.major == 3 and sys.version_info.minor < 9:
                 # double quotes get consumed by windows arg processing
                 ext.define_macros.append(('APSW_USE_SQLITE_AMALGAMATION', '\\"' + path + '\\"'))
             else:
                 ext.define_macros.append(('APSW_USE_SQLITE_AMALGAMATION', '"' + path + '"'))
             ext.depends.append(path)
```

It appears that Python 3.9 uses some different method of invoking the compiler command line that does not eat double-quotes.  I haven't looked further but this appears to fix the issue for me.

**Comment by kmedcalf** [comment]
Ooops.  Change that to:

```
Index: setup.py
==================================================================
--- setup.py
+++ setup.py
@@ -615,11 +615,11 @@
         # SQLite 3
         # Look for amalgamation in our directory or in sqlite3 subdirectory

         path = findamalgamation()
         if path:
-            if sys.platform == "win32":
+            if sys.platform == "win32" and sys.version_info[:2] < (3, 9):
                 # double quotes get consumed by windows arg processing
                 ext.define_macros.append(('APSW_USE_SQLITE_AMALGAMATION', '\\"' + path + '\\"'))
             else:
                 ext.define_macros.append(('APSW_USE_SQLITE_AMALGAMATION', '"' + path + '"'))
             ext.depends.append(path)
```
which also maintains compatibility with Python 2.7 (at least -- thats all I could test)

**Comment by rogerbinns** [comment]
This change did the trick for me:  https://github.com/rogerbinns/apsw/commit/5126d07b2534ed8250da5b1c04144024621a9538

I have run it on 3.9.0, 3.9.1, and all the other versions I do biulds for.  I suspect the underlying Python 3.9 change was fixing how Windows command lines are constructed (a single string) from an argv style list of strings.  The new behaviour is correct.

The other possibility I can think of is maybe you don't have cmd as your shell, and that is what confuses things.  

What error do you see and what does the console show?

**Comment by kmedcalf** [comment]
Yeah, same change.  I think we overlapped on making this change and publishing it.  And yes, I had cmd.exe as the shell, and the error was "unterminated quote" or something like that, but the command line was actually just fine.

**Comment by rogerbinns** [comment]
Thanks for confirming all is good.  Under the hood, apsw.c has this:

    #include AMALGAMATION

The value of AMALGAMATION as seen by the compiler is "sqlite3/sqlite3.c" (including the quotes).  The value is set in the setup.py code, and has to pass through python dealing with it, Python's command line generation, the shell, and the compiler command line processing.  It is very easy for quotes and backslashes to get stripped out in the steps!

**Comment by Mi-La** [comment]
Hi guys!
It seems that it doesn't depend on version of Python, but on version of setuptools - or maybe both :-).
I have Python 3.8.6 (CPython3.8.6.final.0-64), setuptools==60.0.5, and I cannot compile using MSVC:
```
src/apsw.c(49): error C2017: illegal escape sequence
src/apsw.c(49): fatal error C1083: Cannot open include file: 'path_omitted\apsw\sqlite3\sqlite3.c\': No such file or directory
```
When I remove the double quotes hack mentioned above, then it compiles.

It also compiles without changes with older `setuptools==59.8.0`.

**Comment by rogerbinns** [comment]
The root cause is that the amalgamation filename went as a #define through multiple layers of Python modules, cmd, and then into the compiler, and the correct quoting gets lost.  I've now fixed it a different way avoiding filenames - see https://github.com/rogerbinns/apsw/issues/303#issuecomment-1018476475

You can use current master which incorporates that change.

**Comment by Mi-La** [comment]
Just a note - I noticed that similar pattern is still used for sqlite3config.h on master:
https://github.com/rogerbinns/apsw/blob/cf8f630843541d7c050c12a8dd053e3ae5ba48b4/setup.py#L550-L554
Do you think that this one will work? (I don't use sqlite3config.h at all so I cannot test it)

**Comment by rogerbinns** [comment]
@Mi-La thanks for spotting that.  The file only exists if you ran configure which doesn't happen under Windows, so we never end up with a #define of a filename with backslashes and hence don't run into the problem.  But it was worth fixing anyway in https://github.com/rogerbinns/apsw/commit/5c6a7411eae658d78dcffd58684eead7d132e7be
