### ISSUE TITLE
Add support for encode/decode error handling of strings

### ISSUE THREAD

**Issue by CzB404** [rogerbinns/apsw#308]
I've run into an issue that a database I have to process includes a string with invalid UTF-8 bytes.
The problem is that the database in question is not mine, and although it is useful that I caught this error this way, as I can report it to the database's supplier, right now it is more important to me to be able to bind the bad string into an SQL statement and process it. (And the type is important, I can not bind it as a blob.)

Python has the ['surrogateescape'](https://docs.python.org/3/library/codecs.html#error-handlers) error handler for encoders and decoders to handle these situations. It would be useful to be able to supply an error handler to a binding somehow to be able to bind malformed strings in these situations. (Not by default of course!)

**Comment by rogerbinns** [comment]
Are the invalid strings already in the database?  Are you trying to reference one in a query like ````SELECT * WHERE column=?```` and then trying to provide an invalid string as the binding?  Which Python version are you using, and how are you making invalid strings with it?  

There are many potential ways of addressing this, but you'll need to clarify reading the invalid strings versus trying to write invalid strings.

**Comment by CzB404** [comment]
Both reading and writing is needed.

E.g. this SQLite script generates a table with a malformed string:
```SQL
DROP TABLE IF EXISTS t;
CREATE TABLE t(c);
INSERT INTO t VALUES('\xde\xad\xbe\xef');
```

If I attempt to read this database from python:
```python
import apsw

with apsw.Connection('deadbeef.db') as connection:
    cursor = connection.cursor()
    for row in cursor.execute('SELECT c FROM t;'):
        print(row)
```

It results in the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbe in position 2: invalid start byte
```

And even if I manage to get to load the string into Python with the help of the `surrogateescape` error handler there is no way to insert the string into an SQLite database through APSW through binding. I know I could print the string into the script and execute that but I have to process a large amount of similar queries so **the ability to bind** a string this way **is crucial** to me.

```python
import codecs
import apsw

bad_data = b'\xde\xad\xbe\xef'
bad_txt = codecs.decode(bad_data, errors='surrogateescape')

with apsw.Connection('deadbeef.db') as connection:
    cursor = connection.cursor()
    for _ in cursor.execute(
        '''
        DROP TABLE IF EXISTS t;
        CREATE TABLE t(c);
        INSERT INTO t VALUES(?);
        ''',
        (bad_txt,)):
        pass
        
    for row in cursor.execute('SELECT c FROM t;'):
        data_from_txt = codecs.encode(bad_txt, errors='surrogateescape')
        data_from_db = codecs.encode(row[0], errors='surrogateescape')
        if data_from_db != data_from_txt:
            print('Mismatch!')
            print('Original data:', data_from_txt.hex())
            print('Data from DB:', data_from_db.hex())
```

This outputs:
```
Mismatch!
Original data: deadbeef
Data from DB: deadf0bfa3af
```

**Comment by CzB404** [comment]
I also cannot bind the raw binary data in APSW as it would (correctly) bind it as a blob, but in my case it is important that the data is stored as a string.

**Comment by CzB404** [comment]
> **CzB404** commented [1 hour ago](https://github.com/rogerbinns/apsw/issues/308#issuecomment-782859890)
> [...] I know I could print the string into the script and execute that [...]

After some experimentation I have to say that doesn't work, because Python interprets that string as a UTF-8 string. This means that the following script produces different data depending on whether it was first interpreted as a Python literal or a C/C++ string.

```
DROP TABLE IF EXISTS t;
CREATE TABLE t(c);
INSERT INTO t VALUES('\xde\xad\xbe\xef');
```

When executed from C/C++ the database will contain the string `"\xde\xad\xbe\xef"` whereas if executed from Python the database will contain the string `"\xc3\x9e\xc2\xad\xc2\xbe\xc3\xaf"`.

This is not a problem. I'm just writing this down in case someone stumbles across this thread in the future.

**Comment by rogerbinns** [comment]
I'm not really seeing anything I can do with apsw.  Strings are strings and bytes are bytes.  BTW under the hood SQLite stores bytes and strings identically - as a length and the bytes.  The type tag is just different.  That is also why it doesn't verify strings are actually valid byte sequences.

You can do things for reading data:

* Create a view over the tables to return the strings as bytes   (using CAST)
* Or pass them through a user defined function that does the conversions

You can do something similar for writing, eg

   INSERT INTO table (c) VALUES(CAST ? AS STRING)

**Comment by CzB404** [comment]
> I'm not really seeing anything I can do with apsw.

I was thinking that it might be beneficial to make use of the Python codecs module's error handling to process strings when reading and writing strings from a database, e.g. perhaps like this:

```python3
import apsw

with apsw.Connection('deadbeef.db') as connection:
    cursor = connection.cursor()
    for row in cursor.execute('SELECT c FROM t;', errors='<decode/encode error handler>')
        print(row[0])
```

The default value would be 'strict', which would produce the current behavior, but this would allow the passing of 'surrogateescape' which would be useful in my case.

> BTW under the hood SQLite stores bytes and strings identically - as a length and the bytes.

That was understood from the beginning. However my problem is that I am pretty much stuck between a rock and a hard place: the databases aren't mine and the queries that I'm processing are generated by a tool, and the resulting database is also consumed by a tool that is not mine. This makes the type important in my case, no matter how identical the actual storage is.

> You can do things for reading data: [...]
> You can do something similar for writing, eg [...]

Thank you, I completely forgot about `CAST` while trying to find a workaround. However, in my case the generated queries are numerous, and the idea of the script I'm writing is to make use of APSW's `executemany` for handling similar queries. Explicitly handling texts differently throws a wrench in my plans, so to speak. Not impossible to overcome, I admit, but I think adding the usage of Python codecs when passing strings to and from SQLite would greatly benefit APSW's usability:

##### Decoding

It seems like APSW is already implicitly using the 'strict' decoder, so I would think in terms of behavior and performance invoking the decoder directly would not directly impact APSW (besides the ability to specify error handling). The implicit invocation can be demonstrated with this script:

```python3
import apsw

print('Creating a bad string...')
with apsw.Connection(':memory:') as connection:
    cursor = connection.cursor()
    iterator = cursor.execute('SELECT CAST(? AS TEXT);', ([b'\xde\xad\xbe\xef']))
    while True:
        try:
            row = iterator.__next__()
        except StopIteration:
            break
        except UnicodeDecodeError:
            print('Failed creating bad string!')
            exit(1)

        bad_txt = row[0]

print('Finished making bad string!')
print(bad_txt)
```

Produces this output:

```
Creating a bad string...
Failed creating bad string!
```

Indicating that the decoder was called while `__next__()` was executing.

On the other hand, binding strings into queries seem to circumvent encoding, because this script:

```python3
import apsw
import codecs

print('Creating a blob...')
some_original_blob = b'\xde\xad\xbe\xef'
some_original_blob_as_text = codecs.decode(some_original_blob, errors='surrogateescape')
print('Original blob:', some_original_blob.hex())
print('Original blob processed with \'surrogateescape\':', codecs.encode(some_original_blob_as_text, 'utf-32-be', errors='surrogatepass').hex())
print('Processed blob as represented by UTF-8:', codecs.encode(some_original_blob_as_text, 'utf-8', errors='surrogatepass').hex())
print('Processed blob as represented by UTF-16:', codecs.encode(some_original_blob_as_text, 'utf-16-be', errors='surrogatepass').hex())
with apsw.Connection(':memory:') as connection:
    cursor = connection.cursor()
    iterator = cursor.execute('SELECT CAST(? AS BLOB);', ([some_original_blob_as_text]))
    while True:
        try:
            row = iterator.__next__()
        except StopIteration:
            break
        except UnicodeDecodeError:
            print('Failed creating blob!')
            exit(1)

        some_blob = row[0]

print('Finished making blob!')
print(some_blob.hex())
print('Which decoded with UTF-8 represents the following code points:', codecs.encode(codecs.decode(some_blob, 'utf-8', errors='surrogatepass'), 'utf-32-be', errors='surrogatepass').hex())
```

Produces this output:
```
Creating a blob...
Original blob: deadbeef
Original blob processed with 'surrogateescape': 000007ad0000dcbe0000dcef
Processed blob as represented by UTF-8: deadedb2beedb3af
Finished making blob!
deadf0bfa3af
Which decoded with UTF-8 represents the following code points: 000007ad0003f8ef
```

Analyzing this output reveals that:
* `'\xde\xad'` is a valid UTF-8 byte string representing `U+07ad`
* Should UTF-8 conversion occur the resulting blob should be `deadedb2beedb3af`
* Should UTF-16 conversion occur the resulting blob should be `07addcbedcef`
* However the result blob is `deadf0bfa3af`, where `f0bfa3af` is the UTF-8 representation of `U+3F8EF`. Also noteworthy is that blindly interpreting the two low-surrogate characters `dcbe` and `dcef` as a surrogate pair results in the code point `U+13F8EF`. The Python codecs module raises an exception if these bytes are attempted to be decoded as UTF-16 so it doesn't seem like it is invoked here. On the other hand the macros `READ_UTF16LE` and `READ_UTF16BE` in the SQLite codebase look like they would blindly perform this transformation and also seem to perform it in a way that strips the leading hexadecimal `1` from the resulting character.

I think utilizing the Python encoder at value inputs would stabilize the behavior of SQLite as the default encoder error handling (`'strict'`) would guarantee that SQLite receives UTF-8 encoded data.

**Comment by rogerbinns** [comment]
I recognise the position you are in, but I am not going to make the changes to APSW.  Quite simply it is a lot of code, test code, documentation etc.  Note that internally apsw does not use the codecs level API you see, but rather the internal C APIs which take utf-8 directly (and no error handlers since they aren't relevant).

My final suggestion is to write a script that takes the existing database as input, and produces a new one with the string columns containing valid strings.  You may find the code implementing the [shell .dump function](https://github.com/rogerbinns/apsw/blob/master/tools/shell.py#L1015).  Or write something similar in C for better control.

**Comment by CzB404** [comment]
I see. Thank you for your time for looking into this issue.
