### ISSUE TITLE
Relationship to apsw-wheels?

### ISSUE THREAD

**Issue by grantjenks** [rogerbinns/apsw#310]
I'm trying to use apsw in a Heroku-like environment. Unfortunately that means installing from source is difficult. Ideally I'd be able to install a wheel based on instructions from https://rogerbinns.github.io/apsw/download.html#i-really-want-to-use-pip . I noticed that there's an apsw-wheels package on PyPI at https://pypi.org/project/apsw-wheels/ . Is that related to this project? The author of apsw appears to be Roger Binns but the apsw-wheels package on PyPI has maintainer "calebj".

**Comment by rogerbinns** [comment]
Nothing published on pypi has anything to do with me. Unfortunately no one has found a solution to handling configuration.

For example should it use the version of SQLite at the time uploaded to pypi, or the version that is current when installation happens?  Being able to address this kind of thing is the goal.  If you or anyone else could figure out a solution, I'd be delighted.

So various random people have uploaded various random things to pypi.  They generally end up out of date, and picking some arbitrary set of choices (eg an old version of SQLite).

**Comment by grantjenks** [comment]
While I understand the ideal (latest version at installation time), I think most folks would be fine with getting the latest version at the time it was published to PyPI. It’s not ideal but it’s certainly reasonable. I wouldn’t fault the project for that kind of “best effort” approach.

I’d be glad to work with you to figure out a solution here. I believe we could use GitHub Actions to build wheels for the most common platforms. Maybe there could be a nightly GitHub Action that checks for newer SQLite versions and publishes against the latest when available.

Otherwise, I’m afraid I’ll end up like the others, publishing apsw wheels on PyPI. Unfortunately, the “apsw-wheels” package that is currently there contains no information about how the wheels were built and so it’s hard to trust.

**Comment by rogerbinns** [comment]
The difficulty is **not** in tracking versions and doing builds - that has been solved for almost two decades.  Just taking into account the SQLite version, if you were using setup.py then you could use one of these:

    setup.py fetch                              # gets latest version of SQLite when this is run
    setup.py fetch --version 1.2.3.4   # gets specific version
    setup.py                                       # uses system version
    setup.py fetch --version fossil      # uses sqlite current dev version

If you were using PyPI and did ````pip install apsw``` which of the 4 above did you mean?  If I picked one of them as the default, then how do you pick a different choice?  There are other things like which extensions are enabled, enables and omits.  Again I pick a default, but for the half of people for whom the default is wrong, how do they pick a different choice?

**Comment by grantjenks** [comment]
> If you were using PyPI and did pip install apsw which of the 4 above did you mean?

The first option is reasonable. It’s the latest stable version of SQLite at the time the apsw version is published.

> If I picked one of them as the default, then how do you pick a different choice?

Build from source like folks do today. Story doesn’t change for those users.

> There are other things like which extensions are enabled, enables and omits. Again I pick a default, but for the half of people for whom the default is wrong, how do they pick a different choice?

Building against the latest with all extensions enabled again seems reasonable. Certainly there will be users for whom these defaults don’t work but I suspect that is a minority.

Is my proposal to use the latest stable version of SQLite and enable all extensions something that we could “try and see”?

**Comment by rogerbinns** [comment]
The first option is the SQLite version at the time you do pip install.  eg you could install apsw on January 12th and it would get SQLite 1.2.3 and someone else installing on January 13th would get 1.3.3 if that got released inbetween.  In any event I still really don't like this.

What I really want is a means to make the choice.  eg if you could do ````pip install apsw [sqlite=1.2.3.4]```` or ````pip install apsw [sqlite=latest]```` with a similar way of saying it.  That would make the instructions straight forward and result in no surprises for anyone.  I think pip does have a way of doing this, it just hasn't been figured out yet.

**Comment by grantjenks** [comment]
I’m thinking of the first option differently. When I run “pip install”, I want to download a wheel with the sources already compiled. I don’t want to run “fetch” during “install”. So for me, the version of SQLite will be the latest stable at the time the apsw version is uploaded to PyPI. I think of this as the “stable” version because it’s the latest SQLite version that apsw could have been tested against. Does it seem reasonable to upload pre-compiled wheels to PyPI?

The latter option looks interesting. I’m not sure you can use the “=“ syntax but setup.py certainly supports variants. There could be “pip install apsw[sqlite_head]” or “pip install apsw[sqlite_stable]” maybe. Mostly variants are used to select dependencies. They may not be able to run arbitrary commands (“fetch” looks non-standard).

I’d like to understand more about this “ideal”. What if we could upload separate versions for every combination of apsw and SQLite? Like there would be a apsw_1.3_sqlite_1.2 and apsw_1.3_sqlite_1.3, etc. I wouldn’t want to put the full cross-product of versions in PyPI’s global namespace like that but a separate PyPI could host those. 

> In any event I still really don't like this.

That’s fair. It’s your project :)

If I experimented with posting pre-compiled apsw wheels on PyPI or elsewhere, would you be okay with that?

Would you accept a pull request that referenced those wheels at the bottom of the apsw installation page?

**Comment by rogerbinns** [comment]
> I want to download a wheel with the sources already compiled.

That is a relevant piece of information!  Which platform are you using?  Compiling on Windows is essentially impossible for most folks (it takes by far the longest amount of time and hassle when I do releases.)  Having pre-compiled binaries for Linux, MacOS and other platforms (eg BSD) isn't practical due to lack of forward and backward binary compatibility.  Amusingly apsw-wheels does have a random smattering of binary builds although with many combinations missing.

Distributing binaries (which is what you seem concerned with) and distributing source (what I am concerned with) have different issues.

> I’d like to understand more about this “ideal”. 

I want simple instructions for someone to reliably get what they expect, and for things to behave consistently.  eg if you are installing on a new machine every week, how do you ensure you get what you want.  I don't care about the exact syntax and mechanism as long as it works.

> Would you accept a pull request that referenced those wheels at the bottom of the apsw installation page?

Nope.  I have no way of verifying the compiled code is made from the source I publish, or that it would be kept up to date.

**Comment by grantjenks** [comment]
Thanks for the replies, Roger. If I experiment here then I'll let you know.

Great project!

**Comment by rogerbinns** [comment]
BTW which platform did you want binaries for?

**Comment by grantjenks** [comment]
I want them for Linux but I would build them for Windows and Mac too. I’ve done it for a couple of my projects, like scikit-sequitur, using GitHub Actions.

There are also projects like https://github.com/joerick/cibuildwheel which is used by more popular projects, like scikit-learn.

These can’t cover every combination of platform and version but can work for the majority of users.

**Comment by rogerbinns** [comment]
Windows is a whole separate thing, and approximately nobody builds from source there.  I am surprised that you would want "official" Linux binaries, versus building from source to match your distribution exactly!  It looks like cibuildwheel is what apsw-wheels is using.  apsw-wheels also looks like they have been keeping up for two years which is good, and it also seems like they have been building from real source releases, not what is in master branch which some do.

Is there any reason you don't want to use apsw-wheels?

**Comment by grantjenks** [comment]
> I am surprised that you would want "official" Linux binaries, versus building from source to match your distribution exactly!

What am I missing out on? All the functionality seems the same. Is there a significant performance boost you're aware of?

> It looks like cibuildwheel is what apsw-wheels is using.

How can you tell though? I mean, they have the files but I'm wary of unknown binaries that I download from PyPI.

> Is there any reason you don't want to use apsw-wheels?

I'd love to use them. That's where the whole thread started, after all :) I was hoping that maybe you had a pseudonym "calebj" but it seems not. It's hard to trust calebj because it's directly linking to your apsw repository. If they had an open source GitHub repository with the GitHub Actions code that I could audit and check shas then I'd use them tomorrow. I've looked for ways to contact "calebj" but found none.

Would you consider publishing wheels for apsw using cibuildwheel? You could use "apsw-binary" on PyPI or something.

**Comment by rogerbinns** [comment]
The binary side on Linux is nothing to do with performance and all to do with binary compatibility.  Linux aims for source compatibility and running older binaries, but for example it is unlikely that compiling on a newer platform will work on an older one.  There are mismatches that can cause varying amounts of grief!

The filenames seem to match cibuildwheel hence the guess.

Here is a plan going forwards:  apsw will remain a source level distribution with the relevant problems (my biggest concerns) and some Windows binaries (as today).

A separate namespace such as "apsw-binary" then focuses on binary versions, with the more platforms the better.  If you set this up, and also make me a joint administrator on it, then I will link to it from the doc etc.  This way we know it is "official" builds.  As you rightly point out, it should have the source in the open.  There is no need for it to be automatically triggered.

**Comment by grantjenks** [comment]
> There are mismatches that can cause varying amounts of grief!

I think the cibuildwheel package copes with this by using older versions of libs to maximize compatibility.

> Here is a plan going forwards: apsw will remain a source level distribution with the relevant problems (my biggest concerns) and some Windows binaries (as today).

Have you considered reclaiming https://pypi.org/project/apsw/ for yourself? Considering the age of the last update and popularity of this package, I think the PyPI admins would be happy to give it to you. I've done this before and they're typically understanding.

> If you set this up, and also make me a joint administrator on it, then I will link to it from the doc etc.

Can I contribute the code to rogerbinns/apsw ? Would you accept a pull request using a GitHub Action?

**Comment by grantjenks** [comment]
Just providing an update here. I've successfully used pypa/cibuildwheel and pypa/gh-action-pypi-publish in my python-runstats project. You can see an example of the "release" GitHub Action at https://github.com/grantjenks/python-runstats/blob/master/.github/workflows/release.yml I plan to adapt something like this for apsw.

**Comment by calebj** [comment]
As has been mentioned, there's no official relationship between this repo and the one for the wheels, but you can find it [here](https://github.com/calebj/apsw-wheels). I put together the CI flow to help the [Red-DiscordBot](https://github.com/Cog-Creators/Red-DiscordBot) project, and the only attention it needs from time to time is a version bump.

It looks like Appveyor has aged the artifacts from the last build off, and Travis doesn't host artifacts, so unfortunately you can't check that the files match. But since PyPI doesn't allow replacing files after the first upload, you can at least verify that for each tag, the upload in the build logs by twine is what went to PyPI.

I think moving to Github Actions would be far superior to relying on two separate services, and I'd greatly appreciate any help with switching over. I was going through this today to bump the version to 3.36.0 and enable the post-build tests. It seems that pypy has some issues with those, so I will be disabling that target.

**Comment by grantjenks** [comment]
@rogerbinns I've created changes in PR #313 that use GitHub Actions to build binary wheels using cibuildwheel. Would you consider merging this and using it to publish an sdist package and binary wheels to PyPI?

@calebj Feel free to steal the yaml file and use it in your apsw-wheels repo! It should be possible to verify these artifacts since they'll be published on GitHub as part of the action and can be compared with those downloaded from PyPI. The `build.yml` workflow file does all the work :)

**Comment by rogerbinns** [comment]
@calebj APSW doesn't work in practise with pypy - their emulation of the CPython API isn't complete enough.

**Comment by calebj** [comment]
> Feel free to steal the yaml file and use it in your apsw-wheels repo! It should be possible to verify these artifacts since they'll be published on GitHub as part of the action and can be compared with those downloaded from PyPI. The `build.yml` workflow file does all the work :)

Cool, thanks! I'll try to have that set up sometime this weekend.

> APSW doesn't work in practise with pypy - their emulation of the CPython API isn't complete enough.

That was my conclusion as well after some more digging. Disappointing, but understandable.

**Comment by wallies** [comment]
@rogerbinns @grantjenks I work at Kapiche and we use apsw. We put a wheel in https://pypi.org/project/apsw/ just so no one else would take it and put some insecure package there. We would be willing to hand it over when needed

**Comment by rogerbinns** [comment]
@calebj I've merged @grantjenks  [pull request](https://github.com/rogerbinns/apsw/pull/313) and it appears to be good.

I'd like to hook in publishing to pypi for the binaries and apsw-wheels seems like the logical place.  Would you @calebj be willing to work with me on that?  I think all I need is an api token to verify everything is as expected and test.

**Comment by rogerbinns** [comment]
@wallies Thank you for fixing the apsw pypi and your kind offer.  The current plan is to take small steps getting the binary wheels working first, and then revisiting the source pypi.

**Comment by markopy** [comment]
I think it is very confusing to have two different packages on pypi, even if they are official. In my opinion there should only be one apsw pypi package which contains both source and wheels. This is how everyone else does it and causes the least amount of surprise.

Pip will install a wheel if a compatible one is found and otherwise build from source. If the user wants to avoid wheels they can run pip with the `--no-binary` option.

Pip also has `--install-option` which triggers a build from source and allows passing of arbitrary options to `setup.py`. This should cover the use case of wanting to fetch a newer sqlite version at install time.

**Comment by AllSeeingEyeTolledEweSew** [comment]
:+1: for:
 * A single pypi project `apsw`
 * to include binary wheels with statically-linked sqlite
 * and to include a source distribution
 
There's no need to have a separate package `apsw-wheels`.

The official project `cryptography` does exactly this, with openssl. See https://cryptography.io/en/stable/installation/#static-wheels.

My two cents: I think it makes sense to *specify* that the pypi build of `apsw-X.Y.Z` includes sqlite version `X.Y.Z`. I think this is mostly implied by apsw's versioning scheme, and by saying the apsw wheels shall be built with the "latest" sqlite version. But in particular it should be the case that even if you have to rebuild a particular apsw wheel (e.g. due to packaging issues) *and* a newer version of sqlite has been released, that the rebuilt wheel includes its *matching* version of sqlite, *not* the latest version. Since different sqlite versions can have subtly different behavior, I think this is the best way for packages to control the behavior they depend on. As long as apsw and sqlite are packaged *together*, I think this is the sanest way to do it.

**Comment by AllSeeingEyeTolledEweSew** [comment]
@rogerbinns would you accept PRs for pypi upload and/or the change I described above? I've been working on getting libtorrent in pypi over at https://github.com/arvidn/libtorrent/pull/6188, so I'd love to help out here.

**Comment by rogerbinns** [comment]
@AllSeeingEyeTolledEweSew The next release of APSW (3.37.0) is going to be the last that supports Python before 3.6.  Once that release has gone out the intention is to do exactly as you describe.  I was trying to play it safe by using apsw-wheels as an intermediate test bed, but why bother :-)

I'll accept PRs as you describe, but won't do anything with them until 3.37.0 goes out.  I then hope to do a proper publish to pypi a few weeks later.

**Comment by AllSeeingEyeTolledEweSew** [comment]
> I was trying to play it safe by using apsw-wheels as an intermediate test bed, but why bother :-)

One common practice is to use https://test.pypi.org/ as a testbed. That should be sufficient for this change

**Comment by rogerbinns** [comment]
My concern wasn't the pypi bit, but rather people getting surprised such as getting binaries when they expected source or vice versa.  I like to keep APSW as unsurprising as possible.

**Comment by rogerbinns** [comment]
@wallies Can you please add me to apsw on pypi? Account username is rogerbinns and please do verification.

**Comment by wallies** [comment]
@rogerbinns we have added you as owner of apsw. Once you have everything sorted, i think you can remove us as owners/maintainers or leave in case, i will leave that up to your judgement.

**Comment by rogerbinns** [comment]
@wallies thanks for taking care of that so quickly.  My plan is not to change anything until the [automation](https://github.com/rogerbinns/apsw/blob/master/.github/workflows/build.yml) is complete and a full release has been made.

**Comment by rogerbinns** [comment]
APSW 3.38.5-r1 is in [pypi](https://pypi.org/project/apsw/) and all works.  I'll adjust maintainers after the next release in case there are any problems.    @calebj this means you can retire [apsw-wheels](https://pypi.org/project/apsw-wheels/)

**Comment by AllSeeingEyeTolledEweSew** [comment]
Thank you for this. It seriously makes apsw so much more usable in different environments.

**Comment by calebj** [comment]
@rogerbinns would you be able to add aarch64 and armv7l linux builds using uraimo/run-on-arch-action ? Red-DiscordBot has a lot of ARM users that depend on aarch64 (via apsw-wheels) and armv7l (piwheels).

**Comment by rogerbinns** [comment]
@calebj I've updated the cibuildwheel version and workflow [here](https://github.com/rogerbinns/apsw/blob/master/.github/workflows/build-testpypi.yml) which adds aarch64 (and s390 and ppc64) wheels.  Currently shaking it down.

The qemu it installs/configures has this platform list:

linux/amd64 linux/arm64 linux/riscv64 linux/ppc64le linux/s390x linux/386 linux/mips64le linux/mips64 linux/arm/v7 linux/arm/v6

However cibuildwheel doesn't do armv7l as described in [this issue](https://github.com/pypa/cibuildwheel/issues/642).

The [piwheels FAQ](https://github.com/pypa/cibuildwheel/issues/642) says:

> I maintain a package on PyPI. How do I publish it on piwheels?
> 
> You don't need to do anything. All package releases on PyPI are automatically processed by the piwheels project. As long as you upload a source distribution, we'll attempt to build it.

So providing my cibuildwheel updates work, everything should work out for the needs you describe.
