### ISSUE TITLE
Unable to use WAL-mode with custom VFS despite inheriting from VFSFile

### ISSUE THREAD

**Issue by prutschman** [rogerbinns/apsw#311]
I'm attempting to create a custom VFS in python. I'm using Python 3.8.5, and apsw-3.35.4-r1 built from a zip file on Ubuntu 20.04.2 using the "recommended instructions" from the documentation.

I'm not able to get WAL-mode to work if I return a subclass of `apsw.VFSFile` from my `xOpen` method. I've tried both [this minimal example](https://gist.github.com/prutschman/178abd467a0b4eebabd2b99bbebdf9a6) as well as the example obfuscating VFS. In both cases I can use the custom VFS, but attempts to set `pragma journal_mode=wal` are no-ops, and the VFS will refuse to open an existing database that's already in WAL mode.

The linked test creates a fresh database, executes `pragma journal_mode=wal` and then asserts that the return value is `wal`. The first test, which works, uses the default VFS. The second test, which also works, uses a custom VFS with a custom `xOpen` but returns an instance of `apsw.VFSFile`. The third test returns a subclass of `apsw.VFSFile` from its `xOpen`, and it is this configuration that fails.

**Comment by prutschman** [comment]
The documentation for apsw says

> Note: If the VFS that you inherit from supports write ahead logging then your VFSFile will also support the xShm methods necessary to implement wal.

If I'm understanding correctly, this is the responsibility of some code in `apswvfs_xOpen`:
```
  /* If we are inheriting from another file object, and that file
     object supports version 2 io_methods (Shm* family of functions)
     then we need to allocate an io_methods dupe of our own and fill
     in their shm methods. */
  if (Py_TYPE(pyresult) == &APSWVFSFileType)
  {
    APSWVFSFile *f = (APSWVFSFile *)pyresult;
    if (!f->base || !f->base->pMethods || !f->base->pMethods->xShmMap)
      goto version1;
    apswfile->pMethods = &apsw_io_methods_v2;
  }
  else
  {
  version1:
    apswfile->pMethods = &apsw_io_methods_v1;
  }
```

In the case of a subclass of `apsw.VFSFile`, the object will not have a `PyTYPE` of `APSWVFSFileType` but rather the type of the subclass, i.e. `Py_TYPE(pyresult) == &APSWVFSFileType)` is false, but `PyObject_IsInstance(pyresult, &APSWVFSFileType)` is true.

Purely as a test, I tried replacing the type equality check with a call to `PyObject_IsInstance(pyresult, &APSWVFSFileType)`. After doing so, all three of the tests mentioned before allow for successful WAL operation.

I don't claim that this is a proper fix. I know very little about the Python C API, and next to nothing about how multiple inheritance works. (I don't even know if my call to PyObject_IsInstance is correct; it results in a pointer type warning.)

**Comment by rogerbinns** [comment]
It has been a long time since I last touched that code!  I have a vague memory that more fiddly interface code had to be written, along with doc and tests (which take a long time).

My unreliable guess is that the io methods had to be implemented both for Python to C and C to Python calls in order to make inheritance at the C level forward calls correctly for the "class" hierarchy.  If the type is APSWVFSFile then we know no other Python or C code is involved and so can short circuit.

Which sounds complicated, and the doc note means there is no test.  Your solution is almost certainly correct (the pointer warning is not a problem).
