### ISSUE TITLE
Current HEAD segfaulting python after an upgrade

### ISSUE THREAD

**Issue by mattsta** [rogerbinns/apsw#316]
My python started segfaulting using the current commit, but works fine on a previous commit I was using.

I don't have a clean log or trace of where or why it happens (python logging just reports the last `async` entry point in the `faulthandler` dump which isn't the DB operation itself), but the last good commit I used was af405bc74c4d4 so the new error condition happened somewhere in this diff: https://github.com/rogerbinns/apsw/compare/af405bc...eea763e

My usage involves a lot of individual subprocesses launched via `Process()` each doing read-only ops against the DB (with one `Process()` collecting all the writes). It works great under af405bc, but segfault city under eea763e for some reason.

Using python 3.9.8 and complied against sqlite 3.36.0 for both versions.

**Comment by rogerbinns** [comment]
Have you tried the fork checker?

https://rogerbinns.github.io/apsw/apsw.html#apsw.fork_checker

**Comment by mattsta** [comment]
thanks for the pointer! I hadn't seen that before.

I ran with fork_checker enabled and it still crashes using the current repo version, but still works fine if I jump back 10 commits.

I had some time to try and see which commits work, and if I remove this block of commits everything works again: https://github.com/rogerbinns/apsw/compare/efd1a37ea..eea763e

Not sure why removing clear and adding traverse for connection and cursor is segfaulting though unless there's a sneaky null pointer dereference in there somewhere I can't see.

SO! I hooked it up to asan and found a null pointer dereference... but not related to that set of commits. Looks like apsw has a fixed-length 10 element mutex pool thing, but sqlite has 14 mutexes now: https://www.sqlite.org/c3ref/mutex_alloc.html

the extension was compiled with `-DNDEBUG` by default, so the assert() before the static array check isn't in the production code.

So if I compile in debug mode, we get...

```haskell
python3: src/apsw.c:780: apsw_xMutexAlloc: Assertion `which < sizeof(apsw_mutexes) / sizeof(apsw_mutexes[0])' failed.
```

Increasing the `apsw_mutexes` array to [14 elements fixes that crash](https://github.com/sqlite/sqlite/commit/93de6538444cd5065ee7a768ff9240043ef15135).

Though, leaving asan on shows other bad memory accesses with commits between efd1a37ea..eea763e applied, but I couldn't track down why.

Modifications to run with asan:

in `setup.py` add extra args around the `Extension()`:
```python
                              library_dirs=library_dirs,
                              libraries=libraries,
                              define_macros=define_macros,
+                             extra_compile_args = "-O0 -fsanitize=address -g".split(),
```

then run with:

```bash
ASAN_OPTIONS=halt_on_error=0 python blah.py
```

**Comment by rogerbinns** [comment]
Thanks for digging into this and finding the real bug which is that running with asserts, valgrind, asan and any other helpful tools must be part of the release process, and not done less often when I feel like it!  Let's see what happens and I'll find all the latent issues.

(I especially appreciate you bringing this up since the next release is the last one supporting Python >=2.3 and <=3.5 and want to leave that on a high note.  Thanks!)

**Comment by rogerbinns** [comment]
The cause and underlying cause (more comprehensive testing) have been addressed.  Closing.
