### ISSUE TITLE
3.36.0.post1 version on pypi has only Linux files

### ISSUE THREAD

**Issue by cancan101** [rogerbinns/apsw#322]
The [`3.36.0.post1` version of apsw on pypi](https://pypi.org/project/apsw/3.36.0.post1/#files) has only Linux Wheels available for install. No  source version is offered. (for comparison, [see the files for `3.9.2-r1`](https://pypi.org/project/apsw/3.9.2-r1/#files). This means that  when installing apsw on MacOS, the newest version available (without installing from GitHub) is `3.9.2-r1`.

**Comment by rogerbinns** [comment]
I [didn't put that on pypi](https://rogerbinns.github.io/apsw/download.html#easy-install-pip-pypi).

APSW will be coming to pypi soon - see https://github.com/rogerbinns/apsw/issues/310 to continue discussion
