### ISSUE TITLE
rowcount for DML statements

### ISSUE THREAD

**Issue by cancan101** [rogerbinns/apsw#333]
Currently there does not seem to be away to expose a `rowcount` for DML statements. From PEP-249 (bolding is mine):
>**This read-only attribute specifies the number of rows that the last [.execute*()](https://peps.python.org/pep-0249/#id14)** produced (for DQL statements like SELECT) or **affected (for DML statements like UPDATE or INSERT)**.

From [apsw's doc: "DBAPI notes"](https://github.com/rogerbinns/apsw/blob/c8727c595686d7357a97b4ddfef365f9784ffc15/doc/dbapi.rst):
>There is no rowcount. Row counts don't make sense in SQLite any way. SQLite returns results one row at a time, not calculating the next result row until you ask for it. Consequently getting a rowcount would have to calculate all the result rows and would not reduce the amount of effort needed.

However that statement only seems to be true for DQL Statements.

Looking at how [pysqlite3 does it](https://github.com/coleifer/pysqlite3/blob/03081403a1dca0c5085c45e9ed42e26cc97ea752/src/cursor.c#L564):
```c++
        if (self->statement->is_dml) {
            self->rowcount += (long)sqlite3_changes(self->connection->db);
        } else {
            self->rowcount= -1L;
        }
```
where [`is_dml`](https://github.com/coleifer/pysqlite3/blob/f302859dc9ddb47a1089324dbca3873740b74af9/src/statement.c#L84):
```c++
    self->is_dml = !sqlite3_stmt_readonly(self->st);
```

using `sqlite3_changes` and `sqlite3_stmt_readonly` which would need to be exposed in some fashion to calculate `rowcount`.

`rowcount` does seem to be required by the PEP for a DB-API.

**Comment by rogerbinns** [comment]
You can ask for [Connection.changes](https://rogerbinns.github.io/apsw/connection.html#apsw.Connection.changes) which calls ````sqlite3_changes````, and there is also a [changes](https://sqlite.org/lang_corefunc.html#changes) SQL function that gets the same value.

It isn't exposed as a rowcount attribute (DBAPI) style because that is misleading and not how SQLite works.

**Comment by cancan101** [comment]
Is there anything Ike sqlite3_stmt_readonly wrapped to know when to use that method vs hand built logic to count the rows of data returned by a select statement?

**Comment by rogerbinns** [comment]
I'm very confused.  This ticket says DML (modification).

To count the rows returned by a select statement, you count the rows you were returned!  SQLite has no way of knowing how many will be returned until it has returned all of them.

sqlite3_stmt_readonly is not wrapped because prepared statements are not exposed as such (pysqlite3 doesn't either).  I do intend to expose it and sqlite3_stmt_isexplain to the [execution tracers](https://rogerbinns.github.io/apsw/execution.html#execution-tracer).

In general code that wants rowcount is trying to pretend SQLite is Oracle/Postgress, and fighting SQLite!

**Comment by cancan101** [comment]
Correct, I am only interested in rowcount for DML statements. The challenge
I have now is knowing whether or not a given statement is DML such that I
should use Connection.changes to resolve the value for rowcount. If it
isn't DML I assume calling that method will be problematic .

**Comment by rogerbinns** [comment]
I don't know of anything problematic.  changes is the number of rows affected by the last DML.  if you do a DML and then 3 SELECTs and then call changes, you'll get the value from the DML.  Queries don't reset the changes value.

**Comment by cancan101** [comment]
Well that is the problem since if the prior execute was a DQL then I would need to return the size of the return set whereas if the prior execute was a DML I would use this method. I would need to know what the last statement type was to return the right rowcount . Admittedly the rowcount returned in the DQL case has to be calculated synesthetically in my code .

**Comment by rogerbinns** [comment]
I'm still very confused.  It sounds like you want SQLite to behave exactly like how DB-API says (and hence like Oracle/Postgres etc) and always provide rowcounts no matter what SQL was executed.  If that is the case then use the builtin sqlite3 module which tries really hard to paper over the differences.

But if you are using SQLite specifically then you are trying really hard to fight SQLite.  Note the "Lite" in the name.  The SQLite philosophy is to only ask for information you need when you need it, not to gather up stuff in case it might be used.

**Comment by cancan101** [comment]
Correct, I am trying to have SQLite (using `apsw`) behave exactly like (or at least as close as I can get it to) how DB-API says. While getting _everything_ to match _exactly_ is likely beyond the scope of this work, getting `rowcount` to function as in the spec seems within striking distance. I am currently working on a few adapters for [shillelagh](https://github.com/betodealmeida/shillelagh), which leverages apsw, specifically the Virtual Table functionality (the reason I can't just use `sqlite3`). The adapters consumed by sqlalchemy, which expects a DB-API 2. Things currently mostly "work", but there are a few corner cases with conformance to the spec that I am trying to iron out.

To test out conformance to the spec, I have [started working](https://github.com/cancan101/sqlalchemy-apsw) (borrowing heavily from code in shillelagh)  as an `apsw` based Driver for the sqlite Dialect for sqlalchemy. [Sqlalchemy offers a great testing suite](https://github.com/sqlalchemy/sqlalchemy/blob/main/README.dialects.rst) to evaluate the Dialects conformance which I am working through here: https://github.com/cancan101/sqlalchemy-apsw/pull/2. Tests are still failing in a number of places, one of them being on `rowcount`.

**Comment by rogerbinns** [comment]
To be clear I will not add anything to APSW that misleads a user into thinking SQLite works differently than it really does, or that the "cost" of something is different than implied.  That is what pysqlite3 is for.

I am however able to provide reasonable hooks so you can do that kind of thing outside of APSW.  For example that is why [sqlite3pointer](https://rogerbinns.github.io/apsw/connection.html#apsw.Connection.sqlite3pointer) exists which can be used by other C code, or in your case [ctypes](https://docs.python.org/3/library/ctypes.html) would likely be better.

**Comment by cancan101** [comment]
>To be clear I will not add anything to APSW that misleads a user into thinking SQLite works differently than it really does

Sure, I am not asking for that. All I was asking for was for the basic primitives from sqlite to be exposed such that a consume of apsw can implement what is needed. As you pointed out, it looks like `sqlite3_changes64 ` is already wrapped. I believe that `sqlite3_stmt_readonly` would also need to be exposed / wrapped.

I am in no way suggesting that apsw handle all this magic through a `rowcount` property. I totally understand the reasoning why this is left to the user. I'm just asking for the primitives to write the logic myself.

>I am however able to provide reasonable hooks so you can do that kind of thing outside of APSW. For example that is why [sqlite3pointer](https://rogerbinns.github.io/apsw/connection.html#apsw.Connection.sqlite3pointer) exists which can be used by other C code, or in your case [ctypes](https://docs.python.org/3/library/ctypes.html) would likely be better.

this makes sense in the medium term, but it would be nice if the the method were natively wrapped.

**Comment by rogerbinns** [comment]
@cancan101 good news.  As of today's release - 3.39.4.0 - you can easily do this.

First you can set [cursor_factory](https://rogerbinns.github.io/apsw/connection.html#apsw.Connection.cursor_factory)  to produce a cursor instance of your choosing, such as one that complies with dbapi.

Then set an [execution tracer](https://rogerbinns.github.io/apsw/cursor.html#apsw.Cursor.setexectrace) to a method of your choosing.  (Note you can also set the execution tracer on the connection which is used if the cursor doesn't explicitly have one set.)

Finally you have [Cursor.is_readonly](https://rogerbinns.github.io/apsw/cursor.html#apsw.Cursor.is_readonly) which can be used inside the execution tracer to do whatever housekeeping you need.

I am entertaining the idea of apsw.dbapi2 which would provide a dbapi compliant interface.  The best test suite I've found has had no changes in 7 years at https://github.com/baztian/dbapi-compliance
