### ISSUE TITLE
recursive foreign key constraint issue

### ISSUE THREAD

**Issue by Michal-D4** [rogerbinns/apsw#378]
This is an example. What I can do in `sqlite.exe`, and I can't do in my python program with `apsw`:
```
sqlite> .schema dirs
CREATE TABLE dirs (
  id integer PRIMARY KEY NOT NULL,
  path text,
  parentid integer,
  foldertype integer,
  FOREIGN KEY (parentid) REFERENCES dirs (id)
);
```
**I can delete** the row with the id = 25 in **sqlite3.exe**: 
```
sqlite> select * from Dirs where id = 25;
25|new folder|1|2
sqlite> delete from Dirs where ID = 25;
sqlite> select * from Dirs where id = 25;;
sqlite>
```
Inset the row again:
```
sqlite> insert into dirs values (25, 'New folder', 1, 2);
sqlite> select * from Dirs where id = 25;
25|New folder|1|2
sqlite>
```
**Now what happened in my program.** 
Output in window of app (it shows the SQL, bindings and the result below line "---------------"):
```
select * from Dirs where ID = ?
(25,)
----------------------
25; New folder; 1; 2
```
**Now try to delete:**
```
delete from Dirs where ID = ?
(25,)
----------------------
ConstraintError: FOREIGN KEY constraint failed
```
Attempt to hardcode parameter give me the same result:
```
delete from Dirs where ID = 25
----------------------
ConstraintError: FOREIGN KEY constraint failed
```

There are no rows that are children of the row with id = 25:
```
elect * from Dirs where parentID = ?
(25,)
----------------------
```
Python code:
```
def prepare_sql(self, sql, par):
    cursor = self.conn.cursor()
    cur = iter(())
    
    # add into message: SQL, bindings "str(par)", 
    #  and line '"-"*22', separated input from result:
    messages.extend([sql.strip(), str(par), "-"*22])

    try:
        cur = cursor.execute(sql, par)
    except (apsw.BindingsError, apsw.SQLError, apsw.ConstraintError) as er:
        messages.append(to_str(er.args))

    return cur
```
and cursor result:
```
    cursor = self.prepare_sql(sql, par)
    try:
        for cc in cursor:
            messages.append(to_str(cc))
    except (apsw.BindingsError, apsw.SQLError) as er:
        messages.append(to_str(er.args))
```

I am able to delete this row (id=25) with sqlite3.exe without any issue:
```
sqlite> delete from Dirs where ID = 25;
sqlite> select * from Dirs where id = 25;
sqlite>
```

Of course I can switch my program from apsw to sqlite, but hope that you can solve this issue.
Many thanks

**Comment by rogerbinns** [comment]
I am having trouble understanding and hence reproducing what you are reporting.  To be clear, apsw takes calls from Python code and sends them straight to SQLite - it  does not interpret or alter SQLite's behaviour in any way.

Please help by providing a bit more of your data and code that can be run to reproduce.  

What I found:

* foreign_keys enforcement is off by default in both sqlite shell and apsw
* I can't add the 25 row if foreign_keys are on because there is no row id=1
* The schema presented does not prevent deletion, only adding without existing parent_id
* That implies the constraint is elsewhere in the schema

I've attached what I was trying.  It was run like this:
[378.txt](https://github.com/rogerbinns/apsw/files/9944317/378.txt)


     rm -f db ; sqlite3 db ".read 378.txt"

**Comment by Michal-D4** [comment]
Thanks for quick answer.
Sorry. I forgot to mention that the table represents a directory tree and you need to start initialization from the root, something like this:
```
insert into Dirs (ID) values (0)
insert into Dirs (ID) values (1)
insert into dirs values (25, 'New folder', 1, 2);

select * from dirs;
----------------------
0; None; None; None
1; None; None; None
25; New folder; 1; 2
```
But you do not need to reproduce this. I have tried to reproduce this myself in in-memory database and with only this only table.
And everything is working well. 
I forgotten that the mentioned constraint is not the only constraint in the data base and that I forgotten to include 
`pragma foreign_keys = on;' in the sqlite3.exe.

Sorry that i have bothered you with such rubbish and many thanks for your quick answer.
Please close or remove this issue.
Thanks
