### ISSUE TITLE
Build doc flags show as unicode en-dash instead of double-hyphen

### ISSUE THREAD

**Issue by gwk** [rogerbinns/apsw#403]
The documentation generator seems to be doing something weird, translating `--` to `–` (U2013 en-dash character) for all of the bold-face flag table listings. I checked `https://rogerbinns.github.io/apsw/build.html` on both macOS safari and chrome. Note that it only happens in those tables, and not elsewhere in the docs.

This breaks copy-pasting of flags.

**Comment by rogerbinns** [comment]
Thanks for reporting this.  The default true smartquotes setting in Sphinx wasn't being helpful.  The next release (a week or so away) will include rebuilt docs.

**Comment by gwk** [comment]
Great! For the record, I was wrong that it appears only in table listings. It seems to happen anywhere except the code blocks that render to `<pre>`.
