### ISSUE TITLE
Execute Insert does not return any rows

### ISSUE THREAD

**Issue by koramstad** [rogerbinns/apsw#422]
I have this:
`for row in cur.execute('INSERT INTO Items DEFAULT VALUES RETURNING Itm_ID;'):`
`item_id = row[0]`

SQLite3 will return value in this case, but not with APSW.

**Comment by rogerbinns** [comment]
I am unable to repeat your issue.  Here is what I tried:

```python
import apsw

con = apsw.Connection("")
con.execute("""CREATE TABLE t0(
  a INTEGER PRIMARY KEY,
  b DATE DEFAULT CURRENT_TIMESTAMP,
  c INTEGER
);""")

cur = con.cursor()

for row in cur.execute("INSERT INTO t0(c) VALUES(random()) RETURNING c;").fetchall():
    item_id = row[0]

print(item_id)
```

Notes:

* APSW doesn't modify the query going into SQLite or the results coming out, or SQLite's behaviour
* The `fetchall()` bit is harmless, but unnecessary
* There were [bugs in SQLite](https://www.sqlite.org/changes.html#version_3_35_4) that could return nothing in this scenario

To proceed I'll need more code to reproduce and [version information](https://rogerbinns.github.io/apsw/example.html#checking-apsw-and-sqlite-versions)

**Comment by rogerbinns** [comment]
@koramstad Do you have any followup?

**Comment by koramstad** [comment]
Thanks for your support :)
