### ISSUE TITLE
Latest published version (3.41.2.0) contains broken type annotations

### ISSUE THREAD

**Issue by yuri-kilochek** [rogerbinns/apsw#441]
It's already fixed in master though: https://github.com/rogerbinns/apsw/commit/d085172f4419c3d7978714de2b8215e828f6b46a#diff-db5b084c658b4c6fa1d0c1c915243ddb4b934b5e60b9d493fd65eb9d26659180L350

Please publish the fix.

**Comment by rogerbinns** [comment]
A release will be coming out soon corresponding to [SQLite 3.42](https://sqlite.org/draft/releaselog/3_42_0.html)  (note draft in URL).  A new version of mypy came out the other day which helped improve the annotations.

**Comment by rogerbinns** [comment]
The [release has been made](https://github.com/rogerbinns/apsw/releases/tag/3.42.0.0) and it [will also be on pypi in about 90 minutes](https://github.com/rogerbinns/apsw/actions/runs/5005950243).
