### ISSUE TITLE
BEGIN/END becomes BEGIN/COMMIT

### ISSUE THREAD

**Issue by raffaem** [rogerbinns/apsw#454]
The [Tips section of the docs](https://rogerbinns.github.io/apsw/tips.html) says:ù that we can use BEGIN/END to set transaction boundary, but the provided example uses BEGIN/COMMIT, not BEGIN/END:

```
You can use BEGIN/END to set the transaction boundary:

# this will be one transaction
db.execute("BEGIN")
db.execute("INSERT ...")
db.execute("INSERT ...")
db.execute("INSERT ...")
db.execute("COMMIT")
```

**Comment by rogerbinns** [comment]
Thanks for spotting this.  Technically [END is a synonym for COMMIT](https://sqlite.org/lang_transaction.html) and can be followed by an optional TRANSACTION.  But the help text should be clear and unambiguous so I will only use COMMIT.
