### ISSUE TITLE
MisuseError from apsw.log

### ISSUE THREAD

**Issue by Nikratio** [rogerbinns/apsw#459]
Trying to use the example from the [documention](https://rogerbinns.github.io/apsw/tips.html#diagnostics-tips), I get:

```
In [4]: def handler(errcode, message):
   ...:     errstr=apsw.mapping_result_codes[errcode & 255]
   ...:     print (f"SQLITE_LOG: { message } ({ errcode }) { errstr } "
   ...:            + apsw.mapping_extended_result_codes.get(errcode, ""))
   ...:            

In [5]: apsw.config(apsw.SQLITE_CONFIG_LOG, handler)
---------------------------------------------------------------------------
MisuseError                               Traceback (most recent call last)
Cell In [5], line 1
----> 1 apsw.config(apsw.SQLITE_CONFIG_LOG, handler)

MisuseError: MisuseError: error
In [6]: apsw.apswversion()
Out[6]: '3.40.0.0'
```

**Comment by Nikratio** [comment]
For completeness:

```
In [7]: apsw.sqlitelibversion()
Out[7]: '3.40.1'
```

**Comment by Nikratio** [comment]
The above was with apsw shipped from Debian bullseye. Current PyPi version (3.42) seems to work fine.

Is this a known problem in 3.40.0.

**Comment by rogerbinns** [comment]
Before SQLite 3.42 it would only allow the log handler (SQLITE_CONFIG_LOG) to be changed before the full initialization of the SQLite library.  ie you would need to install the log handler immediately after import and before any other operation.  If done after initialization there would be MISUSE_ERROR.

* [SQLite 3.42.0 release notes](https://sqlite.org/releaselog/3_42_0.html) point 3 allowing SQLITE_CONFIG_LOG to occur at any time
* [Commit removing help text](https://github.com/rogerbinns/apsw/commit/10b86bf295b1d0e027f7871bec4b3c76b208330a) explaining MISUSE_ERROR.

**Comment by rogerbinns** [comment]
> Is this a known problem in 3.40.0.

To support SQLite before 3.42 you'll need to install the log handler immediately after import before doing any operations.

The documentation currently only covers the current version.  I've avoided trying to be multi-version due to the complexity and increased workload.

**Comment by Nikratio** [comment]
Hmm. This error started showing up after I *upgraded* my system to current Debian stable. So the same code was working with some past version. Checking ~/.local/lib and /usr/local/lib I also do not see any more recent apsw versions, so I'm pretty sure whatever was shipped with Debian in the previous release supported this. Odd.

**Comment by rogerbinns** [comment]
You probably got lucky in that the install logger call happened before anything else called into SQLite.  All it takes is a site package to disturb things.  For example on Ubuntu [apport](https://wiki.ubuntu.com/Apport) changes `sys.excepthook` which then causes other Python code to behave differently!  Unless you have whole system snapshots it will be hard to diagnose.

Behind the scenes APSW is just calling `sqlite3_config(SQLITE_CONFIG_LOG, handler)` without any sophistication or magic.

**Comment by rogerbinns** [comment]
You can diagnose what is causing SQLite to be initialized:

    $ gdb --args python3 myscript.py
    (gdb) b sqlite3_initialize
    Function "sqlite3_initialize" not defined.
    Make breakpoint pending on future shared library load? (y or [n]) y
    Breakpoint 1 (sqlite3_initialize) pending.
    (gdb) run

**Comment by Nikratio** [comment]
thanks!
