### ISSUE TITLE
Segmentation fault on cursor property `expanded_sql`

### ISSUE THREAD

**Issue by jlintusaari** [rogerbinns/apsw#475]
Hi,

Thanks for the great library! Noticed that the newest version causes a segmentation fault if the `expanded_sql` property is evaluated on a (fresh) cursor. This crashes e.g. interactive shells that automatically evaluate properties of an object in the background.

Minimal example:
```
import apsw
conn = apsw.Connection(':memory:')
conn.cursor().expanded_sql
```

**Comment by rogerbinns** [comment]
Thank you for catching this!
