### ISSUE TITLE
Set SQLITE_MAX_MMAP_SIZE to 1TB (or some other huge value)

### ISSUE THREAD

**Issue by yuri-kilochek** [rogerbinns/apsw#491]
The current default is ~2GB which is too small for 64 bit host.  Since Memory-mapped I/O is opt-in anyway (via `PRAGMA mmap_size`), I see no reason to keep the hard limit.

**Comment by rogerbinns** [comment]
You can compile APSW/SQLite yourself to change this default, although that is somewhat annoying.

I've [posted on the SQLite forum](https://sqlite.org/forum/forumpost/e664376003) to see if we can get the default changed in SQLite itself.

**Comment by rogerbinns** [comment]
No comments on the forum post.  It isn't possible to reliably detect 64 bit compilation in the preprocessor, but it turns out SQLite will clamp SQLITE_MAX_MMAP_SIZE to 2GB on 32 bit anyway.  So I've made the limit 256 terabytes.

**Comment by yuri-kilochek** [comment]
Awesome, thanks!
