### ISSUE TITLE
How do I get second connection to see table immediately after first connection creates it?

### ISSUE THREAD

**Issue by jnrbsn** [rogerbinns/apsw#533]
Hi. I'm guessing this is something I'm doing wrong. I have multiple connections open to the same DB in the same process. In the real code, it's separate threads, but _I don't need separate threads to reproduce it_. I have a situation where a thread might try to select from a table immediately after it's created by another thread. The expected behavior is that I simply get no results, but I get an error saying the table doesn't exist.

```python
import apsw
import apsw.bestpractice

apsw.bestpractice.apply(apsw.bestpractice.recommended)

conn1 = apsw.Connection('db.sqlite')
conn2 = apsw.Connection('db.sqlite')

result = conn1.execute('CREATE TABLE IF NOT EXISTS "foo" ("bar" INT);')
print(f'create table return value: {result!r}')

result = conn2.execute('SELECT * FROM "foo" LIMIT 1;').fetchone()
print(f'select return value: {result!r}')
```

If I delete the DB to make sure the script creates it, I get this:

```
$ rm db.sqlite*
$ python apsw_test.py
create table return value: <apsw.Cursor object at 0x108902b90>
ERROR:root:SQLITE_LOG: no such table: foo in "SELECT * FROM "foo" LIMIT 1" (1) SQLITE_ERROR
select return value: None
```

And then if I run it again without deleting the DB so that the table already exists:

```
$ python apsw_test.py
create table return value: <apsw.Cursor object at 0x10ca02b90>
select return value: None
```

Am I doing something wrong? Is this normal SQLite behavior?

**Comment by rogerbinns** [comment]
Nothing is going wrong, and it is actually working.  You are being thrown by this:

    ERROR:root:SQLITE_LOG: no such table: foo in "SELECT * FROM "foo" LIMIT 1" (1) SQLITE_ERROR

Note that while SQLite is logging that, you are not getting an exception from APSW.  Behind the scenes what is happening is that SQLite is indeed detecting that `conn2` has no table named `foo` based on information in memory, generating the logging error, and then decides to double check the file,  sees that the in-memory information was wrong, rereads the disk contents, re-executes the query and provides the empty results.  I have [reported the problem](https://sqlite.org/forum/forumpost/e4ea2ebbbe) to SQLite.  SQLite does have some [quirks around empty databases](https://sqlite.org/forum/forumpost/342eda89f9bf2581).

If you move the `conn2 =apsw.Connection('db.sqlite')` line to after the `CREATE TABLE` you won't see the message. If you change the select to a non-existent table name, you will see the exception come through as expected.  

As a separate stylistic concern, this code is not as it implies:

    result = conn1.execute('CREATE TABLE IF NOT EXISTS "foo" ("bar" INT);')

That does not provide a result.  `execute` provides an iterator of the zero or more result rows.  This is how SQLite works, and is different than other databases.  SQLite only does the work necessary to provide the first result row, waits for that to be read, does the work for the next result row, waits for that to be read, repeating until all rows are consumed.

Traditionally you would do something like this:

    for row in connection.execute("..."):
        do something with row

You used `fetchone` which only gets the first result row.  You'll find `.get` the most convenient to use.  It gets the full results with the least amount of structure - eg no list if there is only one row, and no tuple if there is only one value.  So this would be what you intended:

  result = connection.execute('CREATE TABLE IF NOT EXISTS "foo" ("bar" INT);').get

`get` is documented [here](https://rogerbinns.github.io/apsw/cursor.html#apsw.Cursor.get).

**Comment by jnrbsn** [comment]
Thanks for reporting the problem to SQLite.

Also, thanks for the info about `get`. My regular code doesn't actually save the return value from the `CREATE TABLE`. I just initially wrote my test script that way to see what it was returning and left it like that.
