### ISSUE TITLE
Support in-memory databases with shared cache

### ISSUE THREAD

**Issue by pydanny** [rogerbinns/apsw#546]
Trying to open an in-memory databases with a shared cache using a URI filename doesn't behave per the Sqlite3 docs: https://www.sqlite.org/inmemorydb.html. Specifically, the Connection class doesn't create an in-memory database, instead it creates a file called `file:memdb3?mode=memory&cache=shared` and loads that:

```python
import apsw
conn = apsw.Connection("file:memdb3?mode=memory&cache=shared")
```

As mentioned, this creates a file called `file:memdb3?mode=memory&cache=shared`:

```sh
ls -l
-rw-r--r--@  1 drg  staff  16384  6 Dec 11:29 file:memdb1?mode=memory&cache=shared
```

I'm using Python 3.12 on OSX 14.7.1.

If there's anything I can do assist with this issue, please let me know.

Thanks for creating and maintaining this awesome library! 🙏🏻

**Comment by rogerbinns** [comment]
To use URI filename parameters you need to use the [SQLITE_OPEN_URI flag](https://www.sqlite.org/c3ref/open.html) or use [apsw.config](https://rogerbinns.github.io/apsw/apsw.html#apsw.config) with the [SQLITE_CONFIG_URI](https://www.sqlite.org/c3ref/c_config_covering_index_scan.html#:~:text=must%20be%20threadsafe.-,SQLITE_CONFIG_URI,-The%20SQLITE_CONFIG_URI%20option) flag to set all opens to use URI by default.

````
# This on each open
conn = apsw.Connection("file:memdb3?mode=memory&cache=shared", 
             flags=apsw.SQLITE_OPEN_URI|apsw.SQLITE_OPEN_READWRITE)

# or this where the config must be done as the very first thing after importing apsw
import apsw
apsw.config(apsw.SQLITE_CONFIG_URI, 1)

# Then you don't need to specify the OPEN flag on each open
conn = apsw.Connection("file:memdb3?mode=memory&cache=shared")
````

**Comment by pydanny** [comment]
That worked! Thanks so much!

**Comment by rogerbinns** [comment]
Heads up - I am omitting shared cache from the next APSW release ([recommended](https://www.sqlite.org/compile.html#recommended_compile_time_options) and use [discouraged](https://sqlite.org/sharedcache.html#use_of_shared_cache_is_discouraged)).

There is an alternative that does the same thing, but is completely undocumented.  (I will add some doc to APSW until SQLite adds doc.)

Use the `memdb` vfs.  These do the trick.  It is crucial that the filename begins with a `.`.
````
conn = apsw.Connection("/name", vfs="memdb")
conn = apsw.Connection("file:/name&vfs=memdb", 
             flags=apsw.SQLITE_OPEN_URI|apsw.SQLITE_OPEN_READWRITE)
````
